ListeEclair/ListeEclair.py

Is it possible to add this to master, please.

bug 8437 and 8584 : ListEclair crash

---

DynamicWeb/po/de-local.po

This is my first translation attempt. Please check for any obvious mistakes.

DynamicWeb: German translation added

---

DynamicWeb/po/de-local.po

Updated German translation for the recent code changes of the dynamic webpage report.

DynamicWeb: Update German translation

---

DynamicWeb/dynamicweb.py
DynamicWeb/report_sets.py
DynamicWeb/templates/dwr_default/data/dwr.js
DynamicWeb/templates/dwr_default/data/dwr_stats.js

* Serial date numbers are used in order to be able to sort dates
* Correct configuration bug (exception)

DynamicWeb report: serial date number & bugfix

---

GraphView/graphview.py

This pull request includes several enhancements to the GraphView addon:
* Make it safe against cycles in the tree. Previously, if any cycles, accidental or otherwise, exist in a tree being graphed, it would cause the GraphView addon to go into infinite recursion until Gramps crashes.
* Traverse the tree upwards from the active person, showing ancestors as well as the descendants. This view, similar to an hourglass graph, makes GraphView extremely useful for navigating the data.
* Make the number of generations to traverse in each direction configurable.

Graphview improvements

---

GraphView/graphview.py

fix a bug due to person_handles changing to a set of handles.
Sorry about missing this case

fix bug in new GraphView code

---

TimelinePedigreeView/TimelinePedigreeView.py

fix several lookups of None handles in TimelinePedigreeView

TimelinePedigreeView - fix few None handle lookups

---

Sqlite/ExportSql.py
Sqlite/ImportSql.py

I tested this with the gramps example data and the output appears to be correct.
Note that the Import also needs to be adjusted.

Make sure the surname handle is unique. Connect surname to name through link table

---

DynamicWeb/po/cs-local.po

https://gramps-project.org/bugs/view.php?id=9620

Initial Czech translation for DynamicWeb addon.

---

RelatedRelativesGramplet/po/nl-local.po

This is my 1st pull request. The only change is in the Dutch title, but when I build, I also see a new version number being generated. Does that mean that I must include the new gpr.py file too? Is the new version number needed to ensure that users see the new Gramplet?

0009482: [Related Relatives Gramplet] duplicate titles

---

GraphView/graphview.py

Handle families outside of looping over person handles to avoid the "Set
changed size during iteration" exception.

GraphView - fix set iteration errors

---

GraphView/graphview.py

Reverts gramps-project/addons-source#32
As per 
https://github.com/gramps-project/addons-source/commit/b8baa42484be97b05dda51a769122ba9f49505a5
`Need to revert #32. `

Revert "GraphView - fix set iteration errors"

---

GraphView/graphview.py

Revert PR #33 and make them right

[GraphView] fix PR #33

---

README.md

best guess as to what each command does?

commands that can be used with a description

---

JSON/JSONImport.py

Removed by https://github.com/gramps-project/gramps/commit/2993d59c2ef45f9f7384b1f03b88d3a183b5ec4c

Reverse commit 5c3da03d2a06c

---

GetGOV/getgov.py

Replaced Type with language-sensitive Type. Prioritized Place Name to be in correct language

Language-sensitive Type and priority

---

NetworkChart/NetworkChart.gpr.py
NetworkChart/NetworkChart.py

NetworkChart ver_0.0.4 release notes.
Added Dialog box to gpr.py file to alert user to missing python modules.  
Link is also provided in dialog to plugin wiki website for instructions.
Fixed highlight bug related to center_person.
All fixes from 0.0.3.

Added dependency dialog with link to wiki

---

ChangeGivenNames/ChangeGivenNames.py
ChangeGivenNames/changenames.glade

Also, fixed transient parent issues
For Gramps42 branch

[ChangeGivenNames]Fix for bug 10044 exception on Windows

---

DenominoViso/DenominoViso.py

Bug From Gramps-users email 
http://gramps.1791082.n4.nabble.com/Place-names-in-DenominoVisio-web-page-td4680631.html

Fix DenominoVisio to use full automatic place name generation

---

PhotoTaggingGramplet/PhotoTaggingGramplet.py
PhotoTaggingGramplet/facedetection.py

https://gramps-project.org/bugs/view.php?id=10164

[PhotoTagging] try to fix face detection

---

GraphView/graphview.py
GraphView/po/ru-local.po

Tags display by color lines in the bottom of person box.
It looks like this:

[GraphView] another way to display tags

---

GraphView/graphview.py
GraphView/po/ru-local.po

Tags display by color lines in the bottom of person box.

[Graph view] tag display[Gramps50]

---

GraphView/graphview.py

**PR description**
New:
- zoom by mouse wheel;
- move graph by middle mouse;
- add button to best fit;
- add button to center on active person;
- remove zoom panel from toolbar.
Changes:
- coef for scale when graph lager than paper applied to operations with graph, so zoom=1 is the similar for large tree and for small;
Fixes:
- positioning on active person;
- flicking when move graph (also fix speed of moving). (Was in PR #52 )

[Graphview] graph zoom and navigation[Gramps51]

---

BiographyQuickview/BiographyQuickview.gpr.py
BiographyQuickview/BiographyQuickview.py

I put together a quickview to make a text summary of a person events for copy pasting to a WikiTree profile (or something similar). 
Example:
Working for me on Gramps 4.2, I haven't tried with a v5 install.

Create new QuickView for Person Biography [gramps42]

---

GetGOV/getgov.py

Fix in 5.0 tree for non-English query to gazetteer. If no place returned by gazetteer, do not create a blank place

GetGOV fix for 0010220

---

DetDescendantReport-images/.gitignore
DetDescendantReport-images/detdescendantreport.gpr.py
DetDescendantReport-images/detdescendantreporti.py

This report is based on the detailed descendant report and has been modified to display as many images as possible.

Add detailed descendant report with images

---

DenominoViso/DenominoViso.py
DescendantsLines/substkw.py
DynamicWeb/dynamicweb.py
NetworkChart/NetworkChart.gpr.py
NetworkChart/NetworkChart.py
PhotoTaggingGramplet/PhotoTaggingGramplet.py

These were already committed to gramps50, and are back-ported to gramps42.  A couple of minor tweaks in some of them to deal with the gpr gramps_target_version change, and to deal with other differences between gramps42 and gramps50.
Each plugin seems to work and to fix the bug associated with it in my testing.
Will need rebuilding when accepted...

Gramps42 some bug fix commits from gramps50 branch

---

GraphView/graphview.py

- class for animation added;
- apply animation for moving to active person (on button click);
- add ability to develop "move to person" feature;
- add combobox with bookmarked persons to navigate to them (if in current tree);
- add shake animation after moving to person.
We need someone who know about threads to look how it realized.
Testing is needed.

Graph view animation [gramps51]

---

GraphView/graphview.py

Should be merger with https://github.com/gramps-project/gramps/pull/523
If dark theme is used - white background looks not good.
- get colors from gtk theme;
- colors for persons and families gets from gramps settings;
- color of links set to font color;

[GraphView] Gtk theme support[Gramps51]

---

HtreePedigreeView/HtreePedigreeView.gpr.py
HtreePedigreeView/HtreePedigreeView.py

Brings in option to show Tags.

H-tree rebase on pedigreeview[gramp50]

---

GoogleEarthWriteKML/GoogleEarthWriteKML.gpr.py
GoogleEarthWriteKML/GoogleEarthWriteKML.py

Provide feedback in log that coordinates are missing for place

GoogleEarthWriteKML output log Missing coordinates[gramps50]

---

PostgreSQL/postgresql.gpr.py

Pops up a message if prerequisites are not present, with pointer to wiki on how to correct.  Option to avoid popup in future.
Note: The addon needs building and listing...

PostgreSQL, check for prerequisites

---

DescendantBooks/CollectAscendants.py

Fixes [#10463](https://gramps-project.org/bugs/view.php?id=10463)
Addon was not properly updated for change in gramps50 filters apply calling parameters.

Fix Descendant Book crash

---

GraphView/MANIFEST
GraphView/gramps-graph.svg
GraphView/graphview.gpr.py
HtreePedigreeView/HtreePedigreeView.gpr.py
HtreePedigreeView/MANIFEST
HtreePedigreeView/gramps-htree.svg
TimelinePedigreeView/MANIFEST
TimelinePedigreeView/TimelinePedigreeView.gpr.py
TimelinePedigreeView/gramps-timelinepedigree.svg

- GraphView
- TimelinePedigreeView
- HtreePedigreeView
- Get around make.py listing error[gramps42]add try/except/pass(prculley)
Backport of PR #115 for Gramps42

Add View specific icons to three addons( #115)[gramps42]

---

GraphView/graphview.py

- add generation spinners to panel for quick switch.
- add_spouses moved to separate method.
- refactor code to make it more good-looking (width < 80 characters where it possible).
- fix comments to look uniform.
- code clean up (fix tabulation, remove unused methods, commented and fixed issues code).
- set descendant generation (1 .. 50) default 10.
- set ancestor generation (0 .. 50) default 3.
- added two spinner controls to the mini toolbar to show more/less generations for ancestors & descendants

[GraphView]refactor code (add_spouses / Animation class) & cleanup[gramps50]

---

NetworkChart/NetworkChart.gpr.py
NetworkChart/NetworkChart.py

Two commits;
* Change this chart to use the standard Name and Date Format options, as well as Language option.
* Pylint

[Network chart]Use standard Name/Language and Date Format options. Pylint code[gramps50]

---

FamilySheet/FamilySheet.py

Fixes [#10468](https://gramps-project.org/bugs/view.php?id=10468)

[FamilySheet]Fix Report exception on missing spouse[gramps50]

---

FamilySheet/FamilySheet.gpr.py
FamilySheet/FamilySheet.py

* Enable CLI (command line) usage
* Enable book report usage
* Add some help tooltips

[FamilySheet]Enable CLI & book report usage /Misc help[gramps50]

---

ImportGramplet/ImportGramplet.py

Fixes [#6752](https://gramps-project.org/bugs/view.php?id=6752)
I suspect that this Gramplet hasn't worked in a long time; I'm not even sure it really has much utility, but @sam-m888 seems to think it might need to work...
I did not test if it can be back-ported to gramps42, although I suspect it can.

Update ImportGramplet to work with gramps50

---

GedcomExtensions/GedcomExtensions.py

Fixes [#10472](https://gramps-project.org/bugs/view.php?id=10472)

Fix Gedcom Extensions Addon for exception on gramps50

---

DynamicWeb/dynamicweb.py

Fixes [#10483](https://gramps-project.org/bugs/view.php?id=10483)
Bug was side effect of the changes for dark theme support...
2nd bug was side effect of changes for place editor...

Fix DynamicWeb for exception on config setting

---

QuiltView/QuiltView.py

Fixes #010488
Add popup for people
Add popup for Families
The popups are copied from Graphview and adapted to this view. Thanks to Ivan.
Be conform to the scheme colours defined in preferences->colors
Add a tooltip when hover a family
Add a search field to facilitate navigation on big trees
Use the defined color for the home person.
Add a progess meter
See PR #128
Fixes #010488

[Quilt View] Apply changes from 5.0 to master

---

GedcomExtensions/GedcomExtensions.py

Fixes [#10515](https://gramps-project.org/bugs/view.php?id=10515)
This should be cherry-picked to Gramp50 etc. as well.

[GedcomExtensions]fix for filtered data[gramps50]

---

DownloadMedia/DownloadMedia.py

Fixes [#10558](https://gramps-project.org/bugs/view.php?id=10558)
Same as PR #135 , only for Gramps50

Fix DownloadMedia to complete when errors are present (Gramps50)

---

ListeEclair/ListeEclair.py

Fixes [#10559](https://gramps-project.org/bugs/view.php?id=10559)
Several fixes as already applied to gramps42 and a couple more to make it work under gramps50.
Progressmeter converted to use 'user' version (to avoid 'no transient parent' warning).
'Entire Database' filter option added.
A couple more placetypes added to report output 'Town', 'Village' etc.
Fixed HandleError crash when trying to lookup non-Event handles as Events.
Fixed crash for persons with no surname.
Fixed issue with invalid dates.

Fixes for ListeEclair addon to work with Gramps50 branch

---

FamilySheet/FamilySheet.py

Needed a TOC for the Books report.
https://gramps-project.org/wiki/index.php?title=Family_Sheet

[FamilySheet]Add Table of Contents inside Book Report[gramps50]

---

SourcesCitationsReport/SourcesCitationsReport.gpr.py
SourcesCitationsReport/SourcesCitationsReport.py

* Make it work
* Mark as "Stable"

[SourcesCitationsReport]Fixs for[gramps50]

---

PrerequisitesCheckerGramplet/PrerequisitesCheckerGramplet.py

Fixes [#10592](https://gramps-project.org/bugs/view.php?id=10592)
Spelling of [successs](https://github.com/gramps-project/addons-source/pull/109#pullrequestreview-119643008) > success  ( @adamvazquez82 )

[PrerequisitesChecker]Fixes UnboundLocalError[gramps50]

---

GetGOV/getgov.gpr.py
GetGOV/getgov.py

Fixes [#10603](https://gramps-project.org/bugs/view.php?id=10603#c54658)
https://gramps-project.org/bugs/view.php?id=10603#c54658

[GetGOV]Fix config setting name[gramps50]

---

ImportMerge/importmerge.py

get_from_name_and_handle doesn't exist anymore

---

GraphView/graphview.py

Change to discuss (refactoring DotGenerator to DotSvgGenerator):
- move generation of SVG data to `DotGenerator.make_svg` from `GraphWidget.populate`;
- handle closing `StringIO()` in `DotGenerator`:
- add `__del__` method to free dot file stream on destroy;
- add `init_dot` method to `DotGenerator` with:
- `StringIO().close()` to free dot file stream;
- writing start data of dot file;
- rename `DotGenerator` to `DotSvgGenerator`;
- `DotSvgGenerator.build_graph` returns dot and svg data, and after `DotSvgGenerator` can be destroyed;
I don't know is this right way and maybe we should not do so refactoring.
Maybe is enough to call `StringIO().close()` on `DotGenerator` deleting (if needed).
Changes:
- sort imports;
- move load bookmarks to `populate` method;
- rename variables;
- add/edit …

[GraphView] code revision and fixes (Gramps50)

---

GraphView/graphview.py

- fix #10791 (escape symbols)
- reduce spaces in family node
- always use html for nodes labels
- review code

[GraphView] fixes (gramps50)

---

DescendantsLines/DescendantsLines.py

DescendantLines had a typo due to sloppy previous commit.

fix a typo

---

DynamicWeb/dynamicweb.py

Fix DynamicWeb when no home person is set

---

PhotoTaggingGramplet/PhotoTaggingGramplet.py

PhotoTaggingGramplet fix right-click menu

---

GenealogyTree/gt_sandclock.py
GenealogyTree/treeplugins.gpr.py

This is modelled after DescendTree which also uses a single class to
reuse as much code as possible. Tested with real data on Gramps 5.0
and basic tests on Gramps 5.1 / master.

GenealogyTree: Add new report for sandclock of family[gramps50]

---

PrerequisitesCheckerGramplet/PrerequisitesCheckerGramplet.py

Update check for Gramps 5.0.1 release.

[PrerequistesCheckerGramplet]Bump Gramps version[gramps50]

---

ClockGramplet/ClockGramplet.py
HtreePedigreeView/HtreePedigreeView.py
QuiltView/QuiltView.py
TimelinePedigreeView/TimelinePedigreeView.py

Fixes [#0010924](https://gramps-project.org/bugs/view.php?id=10924)
Will cherry-pick to master if accepted.

Set correct font resolution for Mac when drawing text directly to cairo.

---

DynamicWeb/templates/dwr_default/data/dwr_start.js

Fixes [#10954](https://gramps-project.org/bugs/view.php?id=10954)

[DynamicWeb]Update OpenStreemaps[gramps50]

---

PrerequisitesCheckerGramplet/PrerequisitesCheckerGramplet.py

Show more complete information about the language environment
Feature request [10952](https://gramps-project.org/bugs/view.php?id=10952)
Adds new section called  "**Locales available:**"

[PreReqChecker]List installed Locales[gramps50]

---

PluginManager/PluginManager.py
PluginManager/po/ru-local.po

Looks better and have builtin delay for search.
https://lazka.github.io/pgi-docs/index.html#Gtk-3.0/classes/SearchEntry.html#Gtk.SearchEntry

[PluginManager] change filter Entry class to SearchEntry[gramps50]

---

PluginManager/po/it-local.po

Added Italian translation for PluginManager addon

---

GraphView/graphview.py

Fixes [#11088](https://gramps-project.org/bugs/view.php?id=11088)

[GraphView]does not show all descendants[gramps50]

---

DenominoViso/DenominoViso.py

Prevent error where default location is in users program files directory on Microsoft windows and other os's
"Failure writing /DenominoViso.xhtml: [Errno 13] Permission denied:
see http://gramps.1791082.n4.nabble.com/DenominoViso-report-error-td4685342.html

Fix file output location for DenominoViso

---

GraphView/graphview.py

Recreation of #199.
PR was reverted since [issue 11161](https://gramps-project.org/bugs/view.php?id=11161#bugnotes).
Now it should work. [fix](https://github.com/gramps-project/addons-source/commit/dfab772359626fdf70ea3910cbef9774e34bdbba)
I have forgot about this [link](https://github.com/gramps-project/addons-source/pull/120#issuecomment-370108363).
Anyway we should test it before merge.

[GraphView] right click menu updates [Gramps50] recreation

---

BirthdaysGramplet/BirthdaysGramplet.gpr.py
BirthdaysGramplet/BirthdaysGramplet.py

Birthdays of people tagged with a selected tag will be ignored by BirthdayGramplet if users wish to hide/ignore them.

[BirthdayGramplet]Add 'ignore birthday' functionality[gramps50]

---

DynamicWeb/po/sk-local.po

Added Slovak translation for DynamicWeb addon

[DynamicWeb] Add Slovak translation [gramps51]

---

HeadlineNewsGramplet/HeadlineNewsGramplet.gpr.py
HeadlineNewsGramplet/HeadlineNewsGramplet.py

clean up
as per https://github.com/gramps-project/addons-source/pull/222

[HeadlineNews]Updates & cleanup[gramps42]

---

DeepConnectionsGramplet/po/ca-local.po

[DeepConnectionsGramplet]Updated Catalan translation[gramps51]

---

DeepConnectionsGramplet/po/ca-local.po

Reverts gramps-project/addons-source#217

Revert "[DeepConnectionsGramplet]Updated Catalan translation[gramps51]"

---

MediaReport/media_report.gpr.py
MediaReport/media_report.py

The **Media Report** is a text report for images. The report allows custom headings and custom notes as well as the image data like notes, citations, tags, attributes and people references. 
* [Wiki dokumentation here](https://gramps-project.org/wiki/index.php/Addon:MediaReport) 
* [Issue #11239 on Bugtracker](https://gramps-project.org/bugs/view.php?id=11239)
**Option Dialog Sample:**
**Sample Report:**

[MediaReport] A media text report [gramps51]

---

FamilySheet/FamilySheet.py

Sort person events by start date

[FamilySheet]Sort person events by start date[gramps51]

---

GraphView/graphview.py

fixes [11155](https://gramps-project.org/bugs/view.php?id=11155)

[GraphView]Add options for Vertical/horizontal spacing between nodes[gramps51]

---

GraphView/graphview.py

Apply gburto01 patch (issue [11033](https://gramps-project.org/bugs/view.php?id=11033))

[GraphView] keep multiple spouses positioned together [gramps51]

---

PhotoTaggingGramplet/PhotoTaggingGramplet.py
PhotoTaggingGramplet/po/ru-local.po
PhotoTaggingGramplet/po/template.pot

Resolve feature request [#11065](https://gramps-project.org/bugs/view.php?id=11065)

[PhotoTaggingGramplet] add age column[gramps51]

---

GraphView/MANIFEST

[GraphView]Fix MANIFEST for Persons Avatars[v51](#235)

---

FilterRules/isrelatedwithfiltermatch.gpr.py
FilterRules/isrelatedwithfiltermatch.py

Feature requested in [#11449](https://gramps-project.org/bugs/view.php?id=11449)
Added as addon as suggested by @prculley in [gramps pull request #954](https://github.com/gramps-project/gramps/pull/954#issuecomment-557195333)

Add new filter rule "related to <filter>"

---

MediaReport/media_report.gpr.py
MediaReport/media_report.py

Feature request [#11348](https://gramps-project.org/bugs/view.php?id=11348)

[MediaReport] Add image size options [gramps51]

---

FilterRules/familieswitheventfiltermatch.gpr.py
FilterRules/familieswitheventfiltermatch.py

Matches families that are matched by an event filter. Requested in [#11499](https://gramps-project.org/bugs/view.php?id=11499)

New filter rule 'familieswitheventfiltermatch'

---

NumberOfAncestorsQuickview/NumberOfAncestorsQuickview.gpr.py
NumberOfAncestorsQuickview/NumberOfAncestorsQuickview.py

As requested in [#9989](https://gramps-project.org/bugs/view.php?id=9989).

Add new quickview report [NumberOfAncestorsQuickview] [gramps51]

---

DynamicWeb/templates/dwr_default/data/dwr.js

Fixes [#11477](https://gramps-project.org/bugs/view.php?id=11477)
User noted that the report had Citation lists and indexes that were not sorted.  This corrects that.

Dynamic Web: Sort the citation lists and indexes[v51]

---

NLWebConnectPack/NLWebPack.gpr.py
NLWebConnectPack/NLWebPack.py
NLWebConnectPack/po/de-local.po
NLWebConnectPack/po/fr-local.po
NLWebConnectPack/po/nl-local.po
NLWebConnectPack/po/template.pot

New plugin NLWebConnectPack based on similar ConnectionPack addons forr other languages, but now with Dutch resources.

[NLWebConnectPack]New plugin[v52]

---

DescendantBooks/DetailedDescendantBookReport.py

- added Report appearances section option

DescendantBooks: 'Report appearances' section option

---

GraphView/graphview.py

Resolve [11583](https://gramps-project.org/bugs/view.php?id=11583)

[GraphView] check for probably death

---

GraphView/graphview.py
GraphView/search_widget.py

Add tooltip with dates and parents information. This help to distinct persons with same names.

[GraphView] add tooltip for person in search

---

FilterRules/isfamilyfiltermatchevent.gpr.py
FilterRules/isfamilyfiltermatchevent.py

As requested on [gramps discourse](https://gramps.discourse.group/t/filter-rule-events-of-families-matching-a-family-filter/273).

New filter rule "Events of families matching a <family filter>"

---

FilterRules/xchromdescendants.gpr.py
FilterRules/xchromdescendants.py

Matches descendants of person following a X-chromosomal inheritance pattern.
[Discussion Thread](https://gramps.discourse.group/t/new-filter-rules-for-genetic-genealogy/352)

New filter rule [X-chromosomal descendants of <person>]

---

FamilySheet/po/nl-local.po

Hi team,
Please, merge modified Dutch translation of addon FamilySheet.
The nl-local.po is updated to latest .pot file.

[FamilySheet]: Dutch translation

---

FRWebConnectPack/po/nl-local.po

Hi,
Please, add Dutch translation into addon FrWebConnectPack.

[FRWebConnectPack]: Dutch translation

---

ChangeGivenNames/po/nl-local.po

Please, add Dutch translation of plugin ChangeGivenNames.

[ChangeGivenNames]: Dutch translation

---

AttachSourceTool/po/nl-local.po

Please, add Dutch translation of addon AttachSourceTool.

[AttachSourceTool]: Dutch translation

---

AvatarGenerator/po/nl-local.po

Please, add Dutch translation of addon AvatarGenerator.

[AvatarGenerator]: Dutch translation

---

NoteCleanup/po/nl-local.po

Please, add Dutch translation of addon NoteCleanup.

[NoteCleanup]: Dutch translation

---

CalculateEstimatedDates/po/nl-local.po

Please, replace Dutch translation of addon CalculateEstimatedDates.

[CalculateEstimatedDates]: Dutch translation

---

CliMerge/po/nl-local.po

Please, add Dutch translation of addon CliMerge.
It is not tested by me, but I don't expect any issues.

[CliMerge]: Dutch translation

---

D3Charts/po/nl-local.po

Please, add Dutch translation of addon D3Charts.
Nevertheless, it seems this addon is not working properly in this version.

[D3Charts]: Dutch translation

---

DEWebConnectPack/po/nl-local.po

Please, add Dutch translation of addon DEWebConnectPack.

[DEWebConnectPack]: Dutch translation

---

DataEntryGramplet/po/nl-local.po

Please, replace Dutch translation of addon DataEntryGramplet.

[DataEntryGramplet]: Dutch translation

---

DateCalculator/DateCalculator.py
DateCalculator/po/nl-local.po

Please, add Dutch translation and modified addon DateCalculator.
Internationalisation of this addon did not work properly.
Both files are tested together in Gramps 5.1.2 without issues.

[DateCalculator]: Dutch translation

---

DeepConnectionsGramplet/po/nl-local.po

Please, replace Dutch translation of addon DeepConnectionsGramplet.

[DeepConnectionsGramplet]: Dutch translation

---

RUWebConnectPack/RUWebPack.gpr.py
RUWebConnectPack/RUWebPack.py
RUWebConnectPack/po/ru-local.po

Russian [Web Connect Pack](https://gramps-project.org/wiki/index.php/Web_Connect_Pack)
Included resources:
- obd-memorial.ru
- pamyat-naroda.ru
- pobediteli.ru
- prozhito.org
- ru.openlist.wiki
- poisk.vid.ru
- vgd.ru
- yandex.ru
- ok.ru
- ria1914.info
- arc.familyspace.ru

Add RUWebConnectPack

---

GraphView/graphview.py

Adds QuickReports and WebConnect submenus to person right-click menu.
Related to popup unification [0004452](https://gramps-project.org/bugs/view.php?id=4452).

[GraphView] submenus for QuickReports and WebConnect

---

RemoveTagTool/RemoveTagTool.gpr.py
RemoveTagTool/RemoveTagTool.py

- allow adding tags too => Add/Remove Tag Tool
- fixes [#11648](https://gramps-project.org/bugs/view.php?id=11648)

RemoveTagTool rewrite

---

PhotoTaggingGramplet/PhotoTaggingGramplet.py

Feature request [0011693](https://gramps-project.org/bugs/view.php?id=11693)

[Photo tagging] add help button

---

FamilyRelationshipTool/FamilyRelationshipTool.gpr.py
FamilyRelationshipTool/FamilyRelationshipTool.py

Requested in [#2656](https://gramps-project.org/bugs/view.php?id=2656)
> (1) Families - when the Relationships of a long list of named fathers and mothers are shown as "Unknown", to change all the "Unknown" to "Married" as a batch.

Add new Tool [FamilyRelationshipTool]

---

DynamicWeb/po/hu-local.po

[DynamicWeb] Hungarian translation

Hungarian localization

---

CombinedView/combinedview.py
CombinedView/po/nl-local.po

Hi team,
Please, add Dutch translation of addon CombinedView.
It's tested in Gramps 5.1.2 without issues after updating internationalisation in combinedview.py

[CombinedView] Dutch translation

---

DetDescendantReport-images/po/nl-local.po

Hi team,
This is the Dutch translation of addon 'DetDescendantReport-images'.
Please, add it into this branch.
A lot of the sentences are already available in Gramps core.
If this addon is fully integrated in Gramps, please consider to remove it.

[DetDescendantReport-images] Dutch translation

---

AllNamesQuickview/po/nl-local.po

[AllNamesQuickview] Updated Dutch translation

---

DescendantCount/po/nl-local.po

Updated Dutch translation for addon DescendantCount.

[DescendantCount] Updated Dutch translation

---

GraphView/po/nl-local.po

Updated Dutch translation for addon GraphView.

[GraphView] Updated Dutch translation

---

ExtendedAttributes/po/nl-local.po

Updated Dutch translation for addon ExtendedAttributes

[ExtendedAttributes] Dutch translation.

---

FaceDetection/po/nl-local.po

Dutch translation for addon FaceDetection
It could NOT tested as this addon is not allowed to load in Gramps.
According to FaceDetection.gpr.py it isn't tested with python3 yet.
Please, add this translation to this branch.

[FaceDetection] Dutch translation

---

FamilyTree/po/nl-local.po

Updated Dutch translation for addon FamilyTree.

[FamilyTree] Updated Dutch translation.

---

FilterRules/po/nl-local.po

Dutch translation for addon FilterRules.

[FilterRules] Dutch translation

---

GeoAncestor/GeoAncestor.gpr.py
GeoAncestor/GeoAncestor.py
GeoAncestor/po/nl-local.po

Updated Dutch translation for addon GeoAncestor.
Localisation repaired.

[GeoAncestor] Localisation fix and Dutch translation

---

GoogleEarthWriteKML/po/nl-local.po

Updated Dutch translation for addon GoogleEarthWriteKML.

[GoogleEarthWriteKML] Updated Dutch translation

---

HtmlView/htmlview.py
HtmlView/po/nl-local.po

Localisation fix and Dutch translation for addon HtmlView.
Not tested because this addon is not added to the download list in Gramps. But perhaps useful later...

[HtmlView] localisation fix and Dutch translation

---

HtreePedigreeView/HtreePedigreeView.py
HtreePedigreeView/po/nl-local.po

Localisation fix and Dutch translation for addon HtreePedigreeView.

[HtreePedigreeView] Localisation fix and Dutch translation

---

ImportGramplet/po/nl-local.po

Updated Dutch translation for addon ImportGramplet.

[ImportGramplet] Updated Dutch translation

---

ImportMerge/po/nl-local.po

Dutch translation for addon ImportMerge.

[ImportMerge] Dutch translation.

---

JSON/po/nl-local.po

Updated Dutch translation for addon JSON.

[JSON] Dutch translation

---

LastChange/po/nl-local.po

Updated Dutch translation for addon LastChange.

[LastChange] Updated Dutch translation

---

NLWebConnectPack/NLWebPack.py
NLWebConnectPack/po/nl-local.po

Added new weblinks to Dutch websites.
Updated Dutch translation.

[NLWebConnectPack] New weblinks and Dutch translation

---

NoteGramplet/po/nl-local.po

Updated Dutch translation for addon NoteGramplet.

[NoteGramplet] Updated Dutch translation.

---

Overview/po/nl-local.po

Dutch translation for addon Overview.

[Overview] Dutch translation

---

PedigreeChart/po/nl-local.po

Dutch translation for addon PedigreeChart.

[PedigreeChart] Updated Dutch translation

---

PhotoTaggingGramplet/po/nl-local.po

Dutch translation for addon PhotoTaggingGramplet.

[PhotoTaggingGramplet] Dutch translation

---

PhpGedView/po/nl-local.po

Dutch translation for addon PhpGedView.

[PhpGedView] Dutch translation

---

PlaceCleanup/po/nl-local.po

Dutch translation for addon PlaceCleanup.

[PlaceCleanup] Dutch translation

---

PluginManager/po/nl-local.po

Dutch translation for addon PluginManager.

[PluginManager] Dutch translation

---

libaccess/po/nl-local.po

Modified Dutch translation for addon libaccess

[libaccess] Modified Dutch translation.

---

PlaceCompletion/po/nl-local.po

Modified Dutch translation for addon PlaceCompletion.

[PlaceCompletion] Modified Dutch translation.

---

PostgreSQL/po/nl-local.po

Dutch translation for addon PostgreSQL.

[PostgreSQL] Dutch translation.

---

PythonGramplet/po/nl-local.po

Updated Dutch translation for addon PythonGramplet.

[PythonGramplet] Updated Dutch translation.

---

Query/po/nl-local.po

Updated Dutch translation for addon Query.

[Query] Updated Dutch translation.

---

RebuildTypes/po/nl-local.po

Dutch translation for addon RebuildTypes.

[RebuildTypes] Dutch translation.

---

RelatedRelativesGramplet/po/nl-local.po

Updated Dutch translation for addon RelatedRelativesGramplet.

[RelatedRelativesGramplet] Updated Dutch translation.

---

RepositoriesReport/po/nl-local.po

Updated Dutch translation for addon RepositoriesReport.

[RepositoriesReport] Updated Dutch translation.

---

SetAttributeTool/po/nl-local.po

Updated Dutch translation for addon SetAttributeTool.

[SetAttributeTool] Updated Dutch translation.

---

SourceIndex/po/nl-local.po

Dutch translation for addon SourceIndex.

[SourceIndex] Dutch translation.

---

Sqlite/po/nl-local.po

Updated Dutch translation for addon Sqlite.

[Sqlite] Updated Dutch translation.

---

SurnameMappingGramplet/po/nl-local.po

Dutch translation for addon SurnameMappingGramplet.

[SurnameMappingGramplet] Dutch translation.

---

TimelinePedigreeView/po/nl-local.po

Updated Dutch translation for addon TimelinePedigreeView.

[TimelinePedigreeView] Updated Dutch translation.

---

TMGimporter/po/nl-local.po

Dutch translation for addon TMGimporter.

[TMGimporter] Dutch translation.

---

ToDoReport/TodoReport.py
ToDoReport/po/ca-local.po
ToDoReport/po/de-local.po
ToDoReport/po/fr-local.po
ToDoReport/po/hr-local.po
ToDoReport/po/it-local.po
ToDoReport/po/lt-local.po
ToDoReport/po/nb-local.po
ToDoReport/po/nl-local.po
ToDoReport/po/pl-local.po
ToDoReport/po/pt_PT-local.po
ToDoReport/po/ru-local.po
ToDoReport/po/sk-local.po
ToDoReport/po/sv-local.po
ToDoReport/po/template.pot

Updated internationalisation and all existing po-files for addon TodoReport.

[TodoReport] Internationalisation fix and translation updates

---

TypeCleanup/po/nl-local.po

Dutch translation for addon TypeCleanup.

[TypeCleanup] Dutch translation.

---

UKWebConnectPack/po/nl-local.po

Updated Dutch translation for addon UKWebConnectPack.

[UKWebConnectPack] Updated Dutch translation.

---

WordleGramplet/po/nl-local.po

Dutch translation for addon WordleGramplet.

[WordleGramplet] Dutch translation.

---

Form/po/nl-local.po

Updated Dutch translation for addon Form.
Tested in Gramps 5.1.2 on Linux Mint 20.

[Form] Updated Dutch translation.

---

EventDescriptionEditor/EventDescriptionEditor.gpr.py
EventDescriptionEditor/EventDescriptionEditor.py

Feature requested in [#4757](https://gramps-project.org/bugs/view.php?id=4757) and [#2656](https://gramps-project.org/bugs/view.php?id=2656)

[EventDescriptionEditor] Add regex support

---

FilterRules/associationsofpersonmatch.gpr.py
FilterRules/associationsofpersonmatch.py

Requested in [#11735](https://gramps-project.org/bugs/view.php?id=11735)

New filter rule "Match associations of <person filter>"

---

FilterRules2/po/nl-local.po
FilterRules2/xchromancestors.py
FilterRules2/xchromdescendants.py

Dutch translation for addon FilterRules2.
Fixed localization in two files.

[FilterRules2] Localization fix and Dutch translation.

---

NumberOfAncestorsQuickview/NumberOfAncestorsQuickview.py
NumberOfAncestorsQuickview/po/nl-local.po

Dutch translation for addon NumberOfAncestorsQuickview.
Fixed localization.
Tested in Gramps 5.1.3 on Linux Mint 20.

[NumberOfAncestorsQuickview] Localization fix and Dutch translation

---

PlaceCoordinateGramplet/po/nl-local.po

Dutch translation for addon PlaceCoordinateGramplet.

[PlaceCoordinateGramplet] Dutch translation.

---

PlaceUpdate/po/nl-local.po

Dutch translation for addon PlaceUpdate.

[PlaceUpdate] Dutch translation.

---

DNA/po/nl-local.po

Dutch translation for addon DNA.

[DNA] Dutch translation.

---

GraphView/graphview.py
GraphView/search_widget.py

To improve search:
- Use `multiprocessing.Process` to search persons;
- Use `threading.Thread` to interact with GUI (live update popover);
- Queues are used to connect Processes and Threads;
- Simultaneous search and GUI update for current graph and all db persons;
Illustrating diagram:
Processes and Threads runing by main Gtk thread (application).
Processes generates 2 queues with found persons (for current graph and for others).
Threads wait for some data in this queues.
As main Gtk thread is locked for other threads we use `GLib.idle_add` to update results in GUI.
Results updating by adding persons one by one (get pending  person from queue, set task by `GLib.idle_add` and wait until it's done);
Warnings:
- ~~May not work on Mac OS X as we use …

[GraphView] Improve search

---

GraphView/graphview.py

Resolve issue [0011846](https://gramps-project.org/bugs/view.php?id=11846).
Need some tests, if it works as expected.

[Graphview] Show all connected persons

---

FilterRules/ageatdeath.gpr.py
FilterRules/ageatdeath.py

Filter rule requested in [#11970](https://gramps-project.org/bugs/view.php?id=11970)

New filter rule [AgeAtDeath]

---

DNA/dnasegmentmap.gpr.py
DNA/dnasegmentmap.py

Initial checkin for DNA Segment Map gramplet. This was forked from the DNAgramplet and extended for multiple associated people, legend with hotlinks, and GEDmatch format import

DNA Segment Map gramplet

---

GraphView/graphview.py
GraphView/search_widget.py

Fixes for Graphview issues:
- [12220](https://gramps-project.org/bugs/view.php?id=12220) (search)
Use `Glib.idle_add` instead of `multiprocessing`.
- [12222](https://gramps-project.org/bugs/view.php?id=12222) (instances)
Fixed by 12220.
- [12225](https://gramps-project.org/bugs/view.php?id=12225) (all-connected recursion exception)
Rewrite building all-connected graph without recursion.
Add restriction to person count (<1000 persons in the graph).

[GraphView] Fix all-connected feature and search

---

DNA/po/nl-local.po

Updated Dutch translation for addon DNA.
Tested without issues in Gramps 5.1.3 on Linux Mint 20.1 (Python 3.8.5).

DNA: Updated Dutch translation.

---

EventDescriptionEditor/po/nl-local.po

Updated Dutch translation for addon EventDescriptionEditor.

EventDescriptionEditor: update Dutch translation

---

EventDescriptionEditor/po/nl-local.po
LifeLineChartView/po/nl-local.po

Updated Dutch translation for addon LifeLineChartView.

LifeLineChartView: update Dutch translation

---

AttachSourceTool/po/nl-local.po
EventDescriptionEditor/po/nl-local.po

Updated Dutch translation for addon AttachSourceTool.

AttachSourceTool: update Dutch translation

---

CombinedView/po/nl-local.po
EventDescriptionEditor/po/nl-local.po

Updated Dutch translation for addon CombinedView.

CombinedView: update Dutch translation

---

EventDescriptionEditor/po/nl-local.po
FilterRules/po/nl-local.po

Updated Dutch translation for addon FilterRules.

FilterRules: update Dutch translation

---

EventDescriptionEditor/po/nl-local.po
GraphView/po/nl-local.po

Updated Dutch translation for addon GraphView.

GraphView: update Dutch translation

---

EventDescriptionEditor/po/nl-local.po
Heatmap/po/nl-local.po

New Dutch translation for addon Heatmap.

Heatmap: new Dutch translation

---

EventDescriptionEditor/po/nl-local.po
NoteCleanup/po/nl-local.po

Updated Dutch translation for addon NoteCleanup.

NoteCleanup: update Dutch translation

---

EventDescriptionEditor/po/nl-local.po
PrerequisitesCheckerGramplet/po/nl-local.po

Updated Dutch translation for addon PrerequisitesCheckerGramplet.

PrerequisitesCheckerGramplet: update Dutch translation

---

EventDescriptionEditor/po/nl-local.po
SetPrivacyTool/po/nl-local.po

Updated Dutch translation for addon SetPrivacyTool.

SetPrivacyTool: update Dutch translation

---

EventDescriptionEditor/po/nl-local.po
SyncAssociations/po/nl-local.po

Updated Dutch translation for addon SyncAssociations.

SyncAssociations: update Dutch translation

---

GraphView/graphview.py

Remember and use the scale setting from the last time Graphview was used rather than use the default setting.

[GraphView] Preserve the scale setting

---

FilterRules/degreesofseparation.py

Fixes [#12426](https://gramps-project.org/bugs/view.php?id=12426) exception

[degreesofseparation] check for person

---

GraphView/po/fr-local.po

French translation update [GraphView]

---

DynamicWeb/templates/dwr_default/data/dwr_body.js

Typo: Added missing quotation mark to form class.

Add missing quotation to form class line 703

---

Form/form_us.xml

The 1950 Census data has been made public and the forms add-on doesn't have it yet

Add 1950 Census

---

GraphView/graphview.py

A feature to show the direct ancestors of the "home" person and any other selected person, back to their common ancestors. For example, in this tree, Ann Abram is the home person.
Selecting "Show path to home person" for Isabel Blundell redraws the tree as follows, showing Isabel & Ann's direct ancestors back to their common ancestors, John & Ellen.

[GraphView] Show direct ancestors of two related people

---

GraphView/graphview.py

New way to add tags in GraphView

---

FamilySheet/po/es_ES.po

Spanish language for FamilySheet

 Spanish language for FamilySheet

---

PrerequisitesCheckerGramplet/po/he-local.po
Themes/po/he-local.po

[Themes] a small fixes to he-local.po v5.2.0

---

GraphView/po/fr-local.po

This reverts commit e259da17d3741706ca9ee8408c9df95c72ce67d3.

Revert "update of french translation (#549)"

---

USWebConnectPack/USWebPack.gpr.py
USWebConnectPack/USWebPack.py

I hope I finally figured out how to get it in 5.1 and not to the master

Update us web pack

---

GrampsWebSync/const.py
GrampsWebSync/diffhandler.py
GrampsWebSync/po/de-local.po
GrampsWebSync/po/de.po
GrampsWebSync/po/template.pot
GrampsWebSync/webapihandler.py
GrampsWebSync/webapisync.gpr.py
GrampsWebSync/webapisync.py

Hi,
this is the first stable version of the addon to synchronize a local Gramps database with a [Gramps Web](https://gramps-project.github.io/web/) instance (more precisely: a Gramps Web API deployment).
The GUI is still not perfect, but the synchronisation of database and media files works.
If/when this is merged, I will add the contents of the beta version's [Readme](https://github.com/DavidMStraub/gramps-addon-webapisync/blob/main/README.md) to the Gramps Wiki.

Add Gramps Web Sync addon

---

ChangeGivenNames/po/nl-local.po
CheckPlaceTitles/po/nl-local.po
DoubleCousins/po/nl-local.po
DynamicWeb/po/nl-local.po
EventDescriptionEditor/po/nl-local.po
FilterRules/po/nl-local.po
FilterRules2/po/nl-local.po
Form/po/nl-local.po
GraphView/po/nl-local.po
S3MediaUploader/po/nl-local.po
SVWebconnectPack/po/nl-local.po
SetPrivacyTool/po/nl-local.po
SharedPostgreSQL/po/nl-local.po

Hi, several Dutch translations have been updated.
Two new Dutch translations are added (S3MediaUploader and SVWebconnectPack)
Please, merge them into this branch (and in master when needed).

Updated Dutch translations of addons

---

SyncAssociations/syncAssociations.py

Removed cM Association. It is deprecated.
Changed Grandfather/Grandmother to Grandparent.

Update default known Associations

---

SharedPostgreSQL/shareddbapi.py
SharedPostgreSQL/sharedpostgresql.gpr.py

@Nick-Hall I'm really sorry but it turned out my fix yesterday #564 was not sufficient because there was an additional error in this statement. Can you please merge & build also this fix? Thanks!

Fix another SQL syntax error

---

GrampsWebSync/grampswebsync.gpr.py
GrampsWebSync/grampswebsync.py
GrampsWebSync/po/de-local.po
GrampsWebSync/webapihandler.py

This handles a few issues repored by users of Gramps Web Sync.

Bug fixes to Gramps Web Sync

---

GrampsWebSync/const.py
GrampsWebSync/diffhandler.py
GrampsWebSync/grampswebsync.gpr.py
GrampsWebSync/grampswebsync.py
GrampsWebSync/webapihandler.py

Dear @prculley,
this is another update of the Gramps Web Sync plugin.
It fixes a bug (related: https://github.com/DavidMStraub/gramps-web-sync/issues/22) and adds a new feature, the option to reset one of the two sides to the other side.

Update GrampsWebSync to version 1.1.0

---

Form/form_ca.xml
Form/form_gb.xml

This updates the two non-ISO compliant files, the rest are already in ISO 8601.

Update Forms definitions to be ISO 8601 dates

---

GenealogyTree/gt_descendant.py

Includes multiple improvements:
bug: move unions to print last
Code Quality: fix variable naming for printing child subgraphs
Enhancement: Option to put first female spouse "left" or "first" to minimize crossings in large trees with multiple marriages
Tested extensively with my own personal trees

GenealogyTree Descendant Tree Report - improved printing for multiple marriages

---

DNA/dnasegmentmap.py

Fixes TSV input to support different thousands separator.

Update dnasegmentmap.py to fix 0013012

---

DNA/dnasegmentmap.py

Fix case where association is a descendant of active

fix bug 13175

---

GraphView/graphview.py
GraphView/search_widget.py

Adding 4 fonctionalities
1 - The possibility to add the gramps ID (option).
2 - The possibility to edit the person or family eventd if they exists.
3 - The search is always using the regexp to have a better selection.
4 - Improve the information in the menu tooltip.
In this case, when the mouse is over a searched person, we can see:
- the birth and/or death date with their respective place,
- the  partners list with birth/death date
- the children list  with birth/death date
- the parents with birth/death date

Graphview search+id+events

---

ToDoReport/TodoReport.py

This pull request adds context to the TODO report as discussed in https://gramps.discourse.group/t/report-for-todo-notes/3674/1
- Context (dates and places) for objects referenced in the report
- Add the ability to filter by note type
- Add the ability to specify the report title
This updates https://github.com/gramps-project/addons-source/pull/562 for gramps52

Todo report context

---

README.md

change examples from gramps50 to gramps52

Update README.md to gramps52

---

DNA/dnasegmentmap.py

Fix dump when DNA Association data contains tab characters.
Add config option to include/exclude Citation Notes for parsing DNA data. Association Notes are always parsed. Currently Citations attached to an Association are parsed too. This makes them optional. 
Add config for character scale in Legend to allow more entries. Default fontsize is 12. This option lets user specify the fontsize for the Legend. This does not impact the chart size.

DNA Segment Map - fix bug 13375 and enhancement 13382

---

DeepConnectionsGramplet/po/he-local.po
RelatedRelativesGramplet/po/he-local.po

New Hebrew Translation for: 
DeepConnectionsGramplet
RelatedRelativesGramplet

New Hebrew translation for DeepConnectionsGramplet and RelatedRelativesGramplet

---

HtmlView/htmlview.py

Related to https://github.com/gramps-project/gramps/pull/1151

HtmlView: Remove unused import

---

DNA/dnasegmentmap.py

Fix parent-child graph for parent view
Move legend in single chromosome view to right side Fix height of drawing area to not obscure either legend or bars Update background colors of maternal/paternal to match other gramps views

Update DNA Segment Map for obscure legend - Feature Request 13421

---

Betawhatsnext/Betawhatsnext.gpr.py
Betawhatsnext/Betawhatsnext.py

the .gpr.py changed to "BETA" status and re-target my repository for the help_url
The main module as several changes:
- added 2 new options: a (partially implemented) verbose suggestion, and; a debug (they will eventually be GUI options)
- added another check for meeting the missing data quota (check at each descendant rather than each completed generation)
- re-format for Black compliance

Change BetaWhatsNext to Beta, add verbose and debug options

---

DNA/dnasegmentmap.py

Fix the edge case where the relationship between 2 people can be determined but there is no common ancestor in the tree. Specifically the relationship leverages siblings where the parent does not exist in the tree.

Fix edge case on common ancestor calc and added visual phasing

---

AllNamesQuickview/po/uk-local.po
DNA/po/uk-local.po
GrampsWebSync/po/uk-local.po
ImportMerge/po/uk-local.po
MediaVerify/po/uk-local.po
PhotoTaggingGramplet/po/uk-local.po
PlaceCleanup/po/uk-local.po
Themes/po/uk-local.po

Add more Ukrainian translations for addons

Add ukrainian translations

---

TimelinePedigreeView/TimelinePedigreeView.py

Bugs where shown when caches were not cleared on DB reload and some cache content was not cleared on (birth) event change/addition

Fix  bug #0013468 

---

DNAMatches/dnamatches.gpr.py
DNAMatches/dnamatches.py
DNAMatches/po/sk-local.po
DNAMatches/po/template.pot

This is the same as the other pull request (https://github.com/gramps-project/addons-source/pull/578), but targeting Gramps 5.2 (dnamatches.gpr.py was updated to target 5.2). From my testing the addon works fine on this version.

New Gramplet: DNA matches (Gramps 5.2)

---

GetGOV/getgov.py

Trap error when using urlopen on GOV site.

Update for GOV site upgrade - Bug 13496

---

DNA/dnasegmentmap.py

X chromosome view for male - grey bar is too long.

DNA Segment Map bug fix 13499

---

GetGOV/getgov.gpr.py
GetGOV/getgov.py

Fix GetGOV after GOV website upgrade. This patch fixes the Mac implementation.

GetGOV fix for Mac due to GOV website upgrade

---

TimePedigreeHTML/TimePedigreeHtml.gpr.py

improve description, 
add wiki help_url

Update TimePedigreeHtml.gpr.py description

---

AvatarGenerator/po/it-local.po

Added Italian translation for AvatarGenerator addon
This pull request adds a complete Italian translation for the AvatarGenerator addon. This will allow Italian-speaking users to use the addon in their native language, improving accessibility and user experience.

Added new Italian translation for AvatarGenerator addon

---

GrampyScript/GrampyScript.gpr.py
GrampyScript/GrampyScript.py
GrampyScript/datadict2.py

This PR adds a new Gramplet (beta) that is a reimagining of SuperTools for Gramps 6.0. It can:
* create tabular data tables
* create simple analysis graphics: bar, pie, and histogram
* can work on entire data, selected data, or filtered data
* can edit primary objects
It is fast, as it builds on the JSON data dictionaries of Gramps 6.0. It has some major differences that I'll outline in discourse and/or wiki page.

New Gramplet: Gram.py Script

---

GrampsChat/GrampsChat.gpr.py
GrampsChat/README.md

Create a README.md as a landing page for the "help_url" attribute in the plugin's registration

Create GrampsChat README.md (needs massaging and proofing)

---

Query/QueryQuickview.py
Query/po/template.pot

Fixes [#13664](https://gramps-project.org/bugs/view.php?id=13664).

Fix format string with unnamed arguments warning

---

SharedPostgreSQL/shareddbapi.py
SharedPostgreSQL/sharedpostgresql.py

Work in progress.
Will leave as draft until ready to merge.

Update SharedPostgreSQL for Gramps 6.0

---

lxml/lxmlGramplet.py

* minor re-organisation into Gtk widgets call (Vertical and Horizontal boxes)
* polish GUI stuff
* GtkDialog mapped without a transient parent was discouraged
* Fix ICON stock and image size on file selector
was Gtk-CRITICAL **: gtk_image_set_from_gicon: assertion 'GTK_IS_IMAGE (image)' failed
* Use LARGE ICON instead of label for the run button
* Move Gtk Entry (file path) and buttons (selector and run), on the same horizontal line.
* Now, it "prints" JSONL content via the TextBuffer on gramplet. So, we can also read and copy from gramps UI. The ERROR dialogs, inherited from lxml (python), are not "children dialogs" into gramps UI manager. So, they can pop-up if the parsing failed. A proper solution should exist, but as they will raise an error anyway, we only get them during debug or …

Dialogs on lxml gramplet

---

WebSearch/WebSearch.gpr.py
WebSearch/assets/csv/us-links.csv
WebSearch/mistral_site_finder.py
WebSearch/model_row_generator.py
WebSearch/openai_site_finder.py

[WebSearch] 6.0 updates including issue https://gramps-project.org/bugs/view.php?id=13751

[WebSearch] 6.0 updates including issue https://gramps-project.org/bugs/view.php?id=13751

---

WebSearch/WebSearch.gpr.py
WebSearch/assets/csv/us-links.csv
WebSearch/mistral_site_finder.py
WebSearch/model_row_generator.py
WebSearch/openai_site_finder.py

5.2 updates including issue https://gramps-project.org/bugs/view.php?id=13751

[WebSearch] 5.2 updates including issue https://gramps-project.org/bugs/view.php?id=13751

---

GraphView/graphview.py

since ConfigParser forces lower case names for keys; harmonize the internal labels to follow
Addresses
https://gramps-project.org/bugs/view.php?id=13399

Bug 13399: change lower case names `graphview-show-id` keys

---

make.py

Addresses https://gramps-project.org/bugs/view.php?id=13777

make.py update for sorting aggregate-pot. Bug 1377

---

GrampsWebSync/grampswebsync.gpr.py
GrampsWebSync/webapihandler.py

See https://gramps.discourse.group/t/gramps-web-gramps-6-0-beta-testers-wanted/7523/38 for the user feedback on the issue that is solved by this.

Update to Gramps Web Sync for 6.0

---

DescendantBooks/README
FilterRules/activepersonrule.py
FilterRules/ageatdeath.py
FilterRules/associationsofpersonmatch.py
FilterRules/degreesofseparation.py
FilterRules/hasrolerule.py
FilterRules/infamilyrule.py
FilterRules/isfamilyfiltermatchevent.py
FilterRules/isrelatedwithfiltermatch.py
FilterRules/multipleparents.py
FilterRules/peopleeventscount.py

Simplify the code and update for gramps 6.0

Update FilterRules addon for Gramps 6.0

---

FilterRules2/matrilinealprogenitrix.py
FilterRules2/mtinheritance.py
FilterRules2/mtinheritanceoffiltermatch.py
FilterRules2/patrilinealprogenitor.py
FilterRules2/xchromancestors.py
FilterRules2/xchromdescendants.py
FilterRules2/yinheritance.py
FilterRules2/yinheritanceoffiltermatch.py

Update rules for combability with Gramp 6.0
Apply black formatting
Add some typing

Update FilterRules2 for compatibility with Gramps 6.0

---

DescendantSpaceTree/DescendantSpaceTree.gpr.py
DescendantSpaceTree/DescendantSpaceTree.py
DescendantSpaceTree/po/template.pot
DescendantSpaceTree/proto/descendant_tree.html
DescendantSpaceTree/webfiles/html/descendant_tree.html
DescendantSpaceTree/webfiles/js/ged_aux.js
DescendantSpaceTree/webfiles/js/tree_base.js

new feature: option to open generated file in browser
new feature: theme option
bug fix: resize and reset graph on browser resize.  clarify modal web help 
bump version to 1.1.0 for new features
regenerate template.pot

DescendantSpaceTree:  Added two features, fixed resize problems
