.travis.yml, DynamicWeb/po/fr-local.po, DynamicWeb/readme.txt, DynamicWeb/run_dynamicweb.py
This PR should allow to pass the CI tests.
All the DynamicWeb tests were excluded from the nostests:
The example reports generation does not work because it seems that in the Travis test environment, the addons are not rebuild and not loaded in the USER_PLUGINS directory.
=> Resolve nosetests conflicts in DynamicWeb report

.travis.yml
When working in a fork, this allows to make the Travis tests use the fork repository and not the git://github.com/gramps-project/* repository
=> Remove useless clone in Travis

GraphView/graphview.py
After changes in "build_graph" definition of "self.person_handles = set()", we can't Include spouses from other marriage not selected by filter in "__add_family".
And I try to find all spouses in "add_descendant" function. I don't know if it's right but It works for me.
=> GraphVeiw: fix 0009460 issue. Multiple spouses.

.travis.yml
When trying to use PRs with source branches different from the base branch (maintenance/gramps50) the travis build would fail because it was using a shell variable for the source branch as the main gramps repo branch name, when it should have been using the base name.
=> Fix travis so it will work from other branches in PRs

PhotoTaggingGramplet/PhotoTaggingGramplet.py
when starting new selection with a person selected.
I have not built this for download/listing.  I also expect that our 'senior developer' will do the merges to master branch...
I also note that the PhotoTaggingGramplet source file is different than the one in the download list for Gramps master. Seems someone made changes and has not rebuilt the plugin since.
If accepted this should also be back-ported to Gramps42 branch...
=> fix bug 10053 PhotoTaggingGramplet exception

TimelinePedigreeView/TimelinePedigreeView.py
When one date (birth or death) is not known, the lifespan would give a huge negative or a huge positive number, leading to excessive lifespan boxes.
=> Fix bug 10058 Timeline View shows infinite lifespans for some persons

BirthdaysGramplet/BirthdaysGramplet.py, DataEntryGramplet/DataEntryGramplet.gpr.py, DataEntryGramplet/DataEntryGramplet.py, DeepConnectionsGramplet/DeepConnectionsGramplet.gpr.py, DeepConnectionsGramplet/DeepConnectionsGramplet.py, DescendantCount/DescendantCount.py, EditExifMetadata/editexifmetadata.py, ExtendedAttributes/ExtendedAttributes.py, FaceDetection/FaceDetection.py, ImportGramplet/ImportGramplet.py, LastChange/LastChangeGramplet.py, MediaBrowser/MediaBrowser.py, NoteGramplet/NoteGramplet.gpr.py, NoteGramplet/NoteGramplet.py, PhotoTaggingGramplet/PhotoTaggingGramplet.py, PythonGramplet/PythonGramplet.py, Query/QueryGramplet.py, RelatedRelativesGramplet/RelatedRelativesGramplet.py, SourceReferences/SourceReferences.py, WordleGramplet/WordleGramplet.py, lxml/etreeGramplet.py, lxml/lxmlGramplet.py
This PR is intended to match the main Gramps gramps50 branch repo https://github.com/gramps-project/gramps/pull/424, that is it does the same things.
Fixes #10089, #10090
I'm pretty sure that none of these changes will hurt compatibility with gramps50 alpha2 so it should be OK to merge this before alpha3 comes out.
I discovered that doing a Family merge that also merged at least one parent, would still get HandleErrors. Root cause, a lot of Gramplets were getting connected to Person history active-changed signal, and thus were doing unnecessary updates. In this case, the Person update occured before the Family Gramplets got shifted off of the family deleted by the merge, so the Gramplets tried to show the (now deleted) family again. And got HandleErrors.
I changed the base Gramplet class …
=> Fixes for Gramplet signalling issues

NetworkChart/NetworkChart.gpr.py, TMGimporter/importtmg.gpr.py
The .gpr files were importing Gtk, which doesn't work for Travis
because there is no display.
=> Fix NetworkChart and TMGimporter to work with Travis (no display)

DescendantCount/DescendantCount.gpr.py, DescendantCount/DescendantCount.py
[Fixes #9981](https://gramps-project.org/bugs/view.php?id=9981)
This Gramplet puts up a list of all people and the number of their descendants.
The original version had several problems, the first and most important was that it took a long time to execute with large dbs and during that time Gramps was unresponsive.
Under v4.2 the Gramplet also updated with every active-change of the Person view, and due to some non-optimal GUI code was updated multiple times for every change.
The algoritm used exhibited a people^2 time function of some sort.  I modified it to operate in approximately linear time with the number of people.  I also modified it to operate only during Gtk 'idle' periods, so the GUI does not go unresponsive, even if it takes some time to run and finish updating the result …
=> Update Descendant Count Gramplet for performance etc.

GraphView/graphview.py
* Fix GraphView for file write errors; use a message, not exception.    Fixes [#10363](https://gramps-project.org/bugs/view.php?id=10363)
* Fix GraphView; Encoding exception when printing on non utf-8 system when unicode chars are present in file.  Found on Windows system with normal cp1252 encoding.  Fixes [#10371](https://gramps-project.org/bugs/view.php?id=10371)
* Fix GraphView for bad transient parent on print file dialog and 'File already exists' dialog.  Fixes [#10372](https://gramps-project.org/bugs/view.php?id=10372)
=> GraphView; some printing issues[gramps42]

NetworkChart/NetworkChart.gpr.py
Fixes #10408
Turns out gramps42 branch doesn't provide 'uistate' to plugins, so there is no easy way to test for CLI mode.  So if dependencies are missing, will end up with a possible GUI dialog even in CLI mode.
Once I got that fixed, there was another stupid bug...
=> Fix NetworkChart gpr to display missing dependencies correctly

PlaceCompletion/PlaceCompletion.py, PlaceCompletion/placecompletion.glade
Fixes  [#10409](https://gramps-project.org/bugs/view.php?id=10409)
Changed re compile options to avoid deprecated 'L' locale option.
Changed Glade file to allow correct transient parent.
Changed Glade file to allow keyboard control over result tree.
Changed Gdk event checks to correctly recognize click and keys.
Fix double change attempt for county/state.
Changed attempt to change county/state to a printed message instead of an error dialog; this doesn't do anything useful with our current enclosed places.  This avoids a click for every place during the scan when using the US state files.
I started this due to bug 10409, however as I began testing I discovered several problems.  The most concerning is that this tool is quite outdated in our current place structure.  While it works, the …
=> Fix PlaceCompletion for some issues

GoogleEarthWriteKML/GoogleEarthWriteKML.gpr.py, GoogleEarthWriteKML/GoogleEarthWriteKML.py
Mentioned in comment https://github.com/gramps-project/addons-source/pull/109#issuecomment-365806328  reported by @adamvazquez82 thank you.
fixes:
> 2018-02-14 15:21:27.187: WARNING: _manager.py: line 295: Plugin error (from 'GoogleEarthWriteKML'): cannot import name 'conv_to_unicode'
and found the second issue:
> TypeError: open_file_with_default_application() missing 1 required positional argument: 'uistate'
=> GoogleMapXML fix 2 errors[gramps50]

Form/form_us.xml, make.py
In order to update the translation of the Form gramplet, `make.py` has to support several xml files. This is done in the first commit. Before the Form's `template.pot` can be updated, an non-ASCII character has to be substituted from the US definitions (second commit). Finally, `template.pot` is updated.
Please check carefully whether these changes make sense. I am neither a python programmer nor a regular translator.
The change of `make.py` probably has to be cherry-picked to the master branch.
=> make.py: support several xml files (eg Form) and update Form's template.pot

CalculateEstimatedDates/CalculateEstimatedDates.py
fixes #10462;  Issue with closing the Progressmeter twice
During testing I found other issues, decided to fix in one PR...
- Issue with HandleError when 'other' person was None
- Db corruption due to wrong deletion of a source if user used "Remove previously added ..."
- Db corruption due to NOT deleting Citations for a deleted source if user used "Remove previously added ..."
- Issue with calling for db rebuild during a transaction (two places)
I suspect that the db corruption issues probably messed up a few db's over the last 5 years...
This should be backported to gramps42 branch...
=> Fix Calculate estimated dates addon[gramps50]

GraphView/MANIFEST, GraphView/gramps-graph.svg, GraphView/graphview.gpr.py, HtreePedigreeView/HtreePedigreeView.gpr.py, HtreePedigreeView/MANIFEST, HtreePedigreeView/gramps-htree.svg, QuiltView/MANIFEST, QuiltView/QuiltView.gpr.py, QuiltView/gramps-quilt.svg, TimelinePedigreeView/MANIFEST, TimelinePedigreeView/TimelinePedigreeView.gpr.py, TimelinePedigreeView/gramps-timelinepedigree.svg
Sam mentioned that it would be nice if the Icons for the various addon charts were different...
Ask, and ye shall receive...
If you want this on gramps42, it is almost the same, but you have to drop the "if locals().get('uistate'):" as uistate is not available on gramps42 branch.  This means that if started in cli mode on gramp42 branch with the plugin present, you may get some (I think harmless) side effects due to the gtk imports.
=> Add View specific icons to four addons[gramps50]

ClipboardGramplet/ClipboardGramplet.py
Issue [#10473](https://gramps-project.org/bugs/view.php?id=10473)
This is the second part of bug10473 (first is https://github.com/gramps-project/gramps/pull/566).
This bug occurs when there is data in the clipboard Gramplet and the db is changed.  An exception occurs because the data was in bytes mode instead of str.
=> Fix Clipboard Gramplet exception with data present when changing db.

ClipboardGramplet/ClipboardGramplet.gpr.py, ClipboardGramplet/ClipboardGramplet.py
Issue [#10475](https://gramps-project.org/bugs/view.php?id=10475)
* Clipboard Gramplet was overriding the 'refresh_objects' method of the listview, I think the original idea was to show clipboard items that were not valid for the current db.  Unfortunately, if a user tried to drag on of these invalid objects (they had a red X for icon) to a reasonable destination, it would create a corrupted db, and usually crash Gramps with HandleError.  The original Clibboard (not Gramplet) was removing these clips from the view entirely, so they could not be erroneously dropped.
* I noted that with some types of clips, the save/restore function of the Clipboard Gramplet would fail because the configure routines don't properly handle a generalized bytes element.  In particular, I saw a '%' in the bytes …
=> [CollectionsClipboardGramplet]Fix for db change and other issues[gramps50]

GraphView/graphview.py, GraphView/po/ru-local.po
Add popup menu for node (on right mouse click).
Simplify add spouse or child to person which doesn't have family.
For node:
`- edit`
`- add new partner`
`- set as home person`
For family:
`- just open editor`
ToDo (in progress, testing and feedback needed):
After graph rebuild scroll to person which have been edited, and not to active person.
=> [GraphView]Add popup menu[gramps50]

GraphView/graphview.py
- fix generation changing (toolbar spinners)
When user change generation spinners values - tree rebuild (populate) will be called with a little delay. So we have more GUI responsiveness and don't have freeze while change values.
I don't know if this is right way to add delay, may widget already have this feature.
- fix empty submenu on person which doesn't have children.
=> [GraphView] fix generation spinners and popup [gramps50]

PrerequisitesCheckerGramplet/PrerequisitesCheckerGramplet.gpr.py, PrerequisitesCheckerGramplet/PrerequisitesCheckerGramplet.py
A diagnostic tool to help work out if users have the [prerequisites](https://github.com/gramps-project/gramps/blob/master/README.md) installed as well as the latest version of Gramps
Also helps on OS's like windows and mac where it's difficult for users to use the command line to get information on gramps via ( gramps -v )!
- Retrieved and updated for Gramps 5
- Added simple Gramps version check
- Displays additional requirements for development & translation.
- Expanded to check all known third-party addons prerequisites
- Tested with Gramps versions: 3.3 to master (Only checked that it loads and displays on older versions)
- Correct min versions for GTK & pygobject (prculley)
- Add check for editexifmetadata addon (prculley)
- Add check for PIL to latexdoc type …
=> Add new PreRequisites Checker Gramplet[gramps50]

DescendantsLines/DescendantsLines.py
[DescendantsLines graphical report] Centered lines are not centered and can overrun the container
Fixes: #[10398](https://gramps-project.org/bugs/view.php?id=10398)
=> [DescendantsLines]Centered lines are not centered and can overrun the container[gramps42]

FamilyTree/FamilyTree.py
Notes with multiple lines attached to  People records can cause the Family Tree graphical report to output the notes outside the boundary of the drawn box or overwrite other text within the drawn box.  To resolve this any carriage returns and new lines are replaced with spaces prior to outputing in the report.
https://gramps-project.org/bugs/view.php?id=10704
=> [FamilyTree]Fix issue with Notes[gramps51]

DescendantBooks/DetailedDescendantBookReport.py, DynamicWeb/dynamicweb.py
Fixes #10720
Since we added caching to the reports, we picked up some errors where the report writer was extending attribute and note lists from cached primary objects. This mostly did not matter, but when a primary object was referenced more than once in a report (like shared events), the extended lists would accumulate all the changes.
I looked in all the reports, searching for ".extend(" or "+=" and inspected to see if it was potentially modifying the cached primary object. If so, I made a copy of the list before using it.
=> Fix reports for shared event attribute and note errors

GenealogyTree/gt_sandclock.py
* Fix for `max_up` if there is more data than the user export.
* Add option `include_siblings` which can be disabled.
* Extend range of generations to allow 0 generations in sandclock.
=> Minor enhancements and fixes for GenealogyTree[gramps50]

README.md, make.py
This updates make.py as-needed function to do a recreation of the *.pot file for any change in a source file found during the as-needed scan.  The recreated .pot file does keep any previous manual header changes.
=> Update make.py as-needed to keep .pot files up to date

GraphView/graphview.py
Move right-click menu to separate class, add actions class.
Add items to menus: remove, tags, bookmarks.
Resolve:
- issue [10870](https://gramps-project.org/bugs/view.php?id=10870)
- @SNoiraud  idea [link](https://github.com/gramps-project/addons-source/pull/195#issuecomment-479144849)
- show images
- highlight the home person
- show full dates
- show places
- show tags
- show animation
- line types >
- direct
- curves
- ortho
- about graph view
- edit
- copy
- remove
- tags >
- select tags for person
- organize tags
- spouses >
- add spouse (new family)
- ... list of spouses ...
- siblings >
- ... list of siblings ...
- children >
- ... list of children ...
- parents >
- ... list of parents ... / add parents
- related >
- ... list of related ...
- set as home person
- add to bookmarks / …
=> [GraphVeiw] right click menu updates [gramps50]

Topola/Topola.gpr.py, Topola/po/pl-local.po, Topola/po/template.pot, Topola/topola.py
Open the addon from the menu: Tools -> Analysis and Exploration -> Interactive Family Tree
A browser tab will be opened with an interactive tree view. See [Topola Genealogy Viewer](https://pewu.github.io/topola-viewer) for examples how the visualization works.
This Gramps addon starts a HTTP server that serves the GEDCOM file that is loaded by the [Topola Genealogy Viewer](https://pewu.github.io/topola-viewer) interface. The user data is not sent to any remote location and only loaded into the browser memory.
=> [Interactive Family Tree]New Addon (Topola)[gramps51]

AvatarGenerator/AvatarGenerator.gpr.py, AvatarGenerator/AvatarGenerator.py
The new addon **AvatarGenerator** allows users to add and remove one or serveral images to a group of filtered people. Users can choose the images from their database. The selected avatar images are only added to people without an image. More information [here](https://gramps-project.org/wiki/index.php/Addon:AvatarGenerator).
Before & After:
=> [AvatarGenerator]Add new addon[gramps50]

RemoveTagTool/RemoveTagTool.gpr.py, RemoveTagTool/RemoveTagTool.py
The Remove Tag Tool addon allows users to remove a tag from a group of objects e.g. persons, events, media. [More information (=Wiki Article)](https://gramps-project.org/wiki/index.php/Addon:RemoveTagTool)
=> New [RemoveTagTool] addon [gramps50]

DynamicWeb/templates/dwr_default/data/dwr_start.js
After asking the OSM support, I was told OSM forward all http request to
https when we use .org url.
So it should work in all cases.
This has an energy cost, so it would be good for the planet to change http
to https.
=> OSM forward all http request to https[gramps52]

HeadlineNewsGramplet/HeadlineNewsGramplet.gpr.py, HeadlineNewsGramplet/HeadlineNewsGramplet.py
Fix two issues with Gramplet.
* Text not wrapping in top section
* Repeating word "Gramplet" in context menu
=> [HeadlineNews]Fix text display & repeating word[gramps51]

HeadlineNewsGramplet/HeadlineNewsGramplet.py
* Check less often for Gramps news on the wiki to reduce Gramps website server load (once a day instead of once an hour).
* Delete obsolete Sourceforge entry as source code is on Github
* update links to secure versions ( http > https )
* update blog links to working versions
* make bugtracker link work again
* General cleanup
=> [HeadlineNews]Updates & cleanup[gramps51]

HeadlineNewsGramplet/HeadlineNewsGramplet.py
* Check less often for Gramps news on the wiki to reduce Gramps website server load (once a day instead of once an hour).
* Delete obsolete Sourceforge entry as source code is on Github
* update links to secure versions ( http > https )
* update blog links to working versions
* make bugtracker link work again
* General cleanup
=> [HeadlineNews]Updates & cleanup[gramps50]

GraphView/graphview.py
To avoid crashing with the "referenced before assignment" error (alternative: `add image_path = None` before `if self.show_images:`)
=> [GraphView]only check image_path when self.show_images=true[gramps51]

AssociationsTool/associationstool.py
Just a minor improvement on the generated output list by also displaying one relation calculated by the relationships module. The idea is to have something for comparison. Maybe a refactoring for generating a more advanced tool which can modify data could be the next step ?
The current utility only displays and returns data set but users may have "directional" issues on textual values set for ASSOciations (e.g., after a gedcoml import). Current output is just a quick way for informing, calling the relationships module can also help users to fix some mistakes on the textual value set as relation.
=> [AssociationsTool]Enhanced by calling relcal[gramps52]

GraphView/graphview.py
Currently Graph View only displays dates which have at least a valid year. This behavior differs from that of other charts (Pedigree, H-Tree). The correct behavior is displaying invalid dates (`MOD_TEXTONLY`) as well when the date is not empty and `show_full_dates` is set to `True`. 
Also the addon currently erroneously displays the birth/death place when `self.show_places==False` and date is empty. Correct behavior: only display place when  `self.show_places==True`
=> [Graph View]Display invalid dates when show_full_dates==True[gramps51]

GraphView/graphview.py
Next attempt to fix [8822](https://gramps-project.org/bugs/view.php?id=8822)
Don't use `font_family_map` and just use `font-family` from SVG.
Screenshots from Windows 
Befor:
After:
=> [Graphview] Label position and font [v51]

GraphView/graphview.py
Now we can choose font. Only font_name and size (not style).
In Windows7 it looks gook for me with `Arial 16`:
=> [GraphView] choose font option [v51]

GraphView/graphview.py
Fix cropping large graph issue.
On my Arch Linux `graphviz` (2.42.2) and it generates scale more then 1 to svg file.
But `GooCanvas.CanvasItem.set_simple_transform` should get (0..1) value.
Seems this happen after `graphviz` 2.40.1 version.
Graphviz issue [link](https://gitlab.com/graphviz/graphviz/issues/1605)
=> [GraphView] fix graphviz scale issue [v51]

NetworkChart/NetworkChart.py
Fixes #11471
Recent Linux systems have started including networkx version 2.x, rather than the older v1.11.  v2.x introduced some incompatibilities, but one in particular was causing the bug.  If/when networkx reaches v3.x, we can expect more such issues.
This Pr makes a minor change to allow either version of networkx to work.
=> Fix NetworkChart to work with v2.x of networkx library

Form/form.py
Fixes #11504
The Forms Gramplet identifies forms by looking at the custom 'Form" attribute on the Source.  Since this is a custom attribute, it never gets translated when storing in the db/xml.  So when you open Gramps in a different language, the comparison to the localized "Form" fails.
The right way to fix this is to add "Form" as a standard AttributeType, so it would be localized in all supported languages.  But that won't happen quickly.  In the meantime, I have made the comparison to all the current languages that Forms supports.  It looks like it works for me.
=> Fix Forms Gramplet to allow forms to be retrieved when language changes

GenealogyTree/gt_ancestor.py, GenealogyTree/gt_descendant.py, GenealogyTree/gt_grandparent.py, GenealogyTree/gt_sandclock.py
This can be useful for setting (and testing) a locale value on genealogytree.
Currently the date format is in english only.
See also https://github.com/gramps-project/gramps/pull/960
=> [LaTeX genealogytree]Add the Language selector[v51]

AncestorFill/po/nl-local.po, MediaReport/media_report.py, MediaReport/po/nl-local.po
Hi team,
Unfortunately I made two commits in one branch, so now I have translations for two different addons. Sorry, I'm a beginner with Git/Github...
1] for MediaReport addon I had to modify media_report.py to get internationalization working. So you find nl-local.po with Dutch translation and a modified media_report.py.
2] for AncestorFill addon I've included nl-local.py file with Dutch translation.Though the translation works fine within Gramps I found that the generated reports unfortunately are not translated.
Please, add these changes into Gramps.
Thanks in advance!!
Kind regards,
Jan Sparreboom
=> Dutch translation for addons AncestorFill and MediaReport

Form/form_gb.xml
Update the UK census forms defined in form_gb.xml to include additional <_longname> elements.
The element text is taken from the working on the orignal census form.
No documentation change required. 
Backwards compatible.
=> Form: Add Additional _longname Elements to Form_GB

Form/form_gb.xml
Add additional form headings for UK1891, UK1901 and UK1911 forms
Existing forms will continue to work correctly and will show the new headings.
1911 Postal Address was not added. Logically this can use the Event place field.
No documentation update required.
=> Form: Add additional headings for UK1891, UK1901 and UK1911 forms.

EventDescriptionEditor/EventDescriptionEditor.gpr.py, EventDescriptionEditor/EventDescriptionEditor.py
The Event Description Editor tool allows users to select several events, search their event descriptions for a substring and change the description or the substring to a new one. This feature was requested in [#4757](https://gramps-project.org/bugs/view.php?id=4757) and in [#2656](https://gramps-project.org/bugs/view.php?id=2656).
=> Add new addon [EventDescriptionEditor] [gramps51]

Sqlite/tests/test_sqlite.py
The travis test is using master for the gramps side of the tests; which has been modified to use only sqlite db.  This changes the sqlite test to use sqlite db instead of bsddb.
=> Fix Sqlite addon to use sqlite for the gramps db instead of bsddb

NetworkChart/NetworkChart.py, NetworkChart/po/nl-local.po, NetworkChart/po/template.pot
Please, add Dutch translation of addon NetworkChart.
Besides, please check the modified NetworkChart.py because internationalization is not working properly.
And template.pot is modified, added line 1026. This is important for other translators of this addon.
-----------------------------------------------------------------------------------------------------
NetworkChart.py String in line 1026 is not internationalized:
1026    cfill_female_alpha = NumberOption("Female Background Alpha",
Modified:
1026    cfill_female_alpha = NumberOption(_("Female Background Alpha"),
Added in nl-local.po:
#: NetworkChart/NetworkChart.py:1026
msgid "Female Background Alpha"
msgstr "Alpha achtergrond bij vrouwen" …
=> [NetworkChart]: Dutch translation and add internationalization

AssociationsTool/po/nl-local.po
Please, add Dutch translation of addon AssociationsTool.
=> [AssociationsTool]: Dutch translation

BiographyQuickview/BiographyQuickview.py, BiographyQuickview/po/nl-local.po, BiographyQuickview/po/template.pot
Please, add Dutch translation of addon BiographyQuickview.
Localisation was not implemented.
Added:
Line 25:
#------------------------------------------------------------------------
#
#
#------------------------------------------------------------------------
from gramps.gen.const import GRAMPS_LOCALE as glocale
try:
trans = glocale.get_addon_translator(__file__)
except ValueError:
trans = glocale.translation
_ = trans.gettext
ngettext = trans.ngettext
Modified line 48:
sd.title(_("Biography for %s") % sa.name(person))
Modified line 92:
sd.header1(_('Sources'))
Created new pot-file.
=> [BiographyQuickview]: Dutch translation and add internationalization

BirthOrder/po/nl-local.po
Please, add Dutch translation of addon <>.
It's tested in Gramps 5.1.2, unfortunately with two issues.
**Issues**:
Current Sort:     fields Name and Birth Date are not translated.
Proposed Sort:  fields Name and Birth Date are not translated.
As far as i can tell both fields come from different code than this addon.
=> [BirthOrder]: Dutch translation

BirthdaysGramplet/po/nl-local.po
Please, add Dutch translation of addon BirthdaysGramplet.
It's tested in Gramps 5.1.2, with one minor issue which has nothing to do with the translation itself.
Issue:
The translation is only activated after the gramplet has been removed and then added again.
Simply restarting Gramps was not enough.
But
=> [BirthdaysGramplet]: Dutch translation

CheckPlaceTitles/po/nl-local.po
Please, replace Dutch translation of addon CheckPlaceTitles.
It is NOT tested in Gramps 5.1.2 as this addon isn't installed and I can't find it...
Maybe this addon is not needed anymore, see: https://gramps-project.org/wiki/index.php/GEPS_045:_Place_Model_Enhancements
=> [CheckPlaceTitles]: Dutch translation

ClipboardGramplet/po/nl-local.po
Please, replace Dutch translation of addon ClipboardGramplet.
=> [ClipboardGramplet]: Dutch translation

ClockGramplet/po/nl-local.po
Please, replace Dutch translation of addon ClockGramplet.
=> [ClockGramplet]: Dutch translation

DenominoViso/DenominoViso.py, DenominoViso/po/nl-local.po, DenominoViso/po/template.pot
Please, replace Dutch translation of addon Denominoviso.
Modified DenominoViso.py to make translation possible for:
Included/Excluded (lines 2913/2914)
onclick/onmouseover (lines 3020/3021)
Unfortunately more words are not translated, such as the contents of the columns relation type and Source confidence color, but the origin of these cannot be found in this addon.
Modified template.pot, adding new words as described above.
=> [Denominoviso]: Dutch translation

Themes/po/nl-local.po, Themes/themes.py
Please,  add Dutch translation of addon Themes.
It has been tested in Gramps 5.1.2 after some issues with internationalisation part in themes.py.
See code changes below.
=> [Themes] Dutch translation

LinesOfDescendency/lines-of-descendency.py, LinesOfDescendency/po/de-local.po, LinesOfDescendency/po/fr-local.po, LinesOfDescendency/po/nl-local.po, LinesOfDescendency/po/template.pot
Hi team,
Hereby an update for the LinesOfDescendency addon.
Unfortunately, the translation appeared to work only partially, namely only the startup screen. The generated report was not translated, so I made two changes to the source code.
Also made a new template.pot and updated three translations (DE, FR, NL).
All this has been tested in Gramps 5.1.2 without any problems.
Hopefully you can handle these adjustments?
=> [Lines of descendency] Localisation update and new translations

DescendantBooks/po/nl-local.po
Hi team,
Please, add Dutch translation of addon Descendant books.
It's tested in Gramps 5.1.2 with minor issues. The translation of following lines doesn't work during report generating:
#: DescendantBooks/CollectAscendants.py:178
#, python-format
msgid "Deep pruning ascendants from %s people..."
msgstr "Krachtig bloedverwanten in opgaande lijn reduceren van %s personen..."
#: DescendantBooks/CollectAscendants.py:182
#, python-format
msgid "Pruning ascendants from %s people..."
msgstr "Bloedverwanten in opgaande lijn reduceren van %s personen..."
Maybe that translation is overridden by translation in Gramps core?
In any case, it is not very disturbing.
=> [Descendant books] Dutch translation

DetId/po/nl-local.po
Dutch translation for addon Deterministic ID.
=> [Deterministic ID] Dutch translation

Differences/differences.py, Differences/po/de-local.po, Differences/po/fr-local.po, Differences/po/nl-local.po, Differences/po/template.pot
Updated internationalisation for addon Differences.
Translation didn't work correctly and some often used items were not translated.
Based on this update of differences.py a new template.pot created.
Updated DE, FR, NL po-files based on new template.
=> [Differences] Addon update and new translations DE, FR, NL

ExportProlog/po/nl-local.po
Updated Dutch translation for addon ExportProlog.
=> [ExportProlog] New Dutch translation

ExportRaw/po/nl-local.po
Updated Dutch translation for addon ExportRaw
=> [ExportRaw] Updated Dutch translation

ExtractCity/extractcity.py, ExtractCity/po/nl-local.po
Repaired most of localisation and added new Dutch translation for addon ExtractCity.
Tested with one issue in Gramps 5.1.2 on Linux Mint 20: button 'Toggle Selected' doesn't translate.
=> [ExtractCity] Repaired localisation and Dutch translation.

GedcomExtensions/po/nl-local.po
Dutch translation for addon GedcomExtensions.
=> [GedcomExtensions] Dutch translation

GenealogyTree/gt_ancestor.py, GenealogyTree/gt_descendant.py, GenealogyTree/gt_grandparent.py, GenealogyTree/gt_sandclock.py, GenealogyTree/po/nl-local.po
Dutch translation for addon GenealogyTree.
Localisation repaired.
Tested with no issues in Gramps 5.1.2 on Linux Mint 20.
=> [GenealogyTree] Localisation fix and Dutch translation

GetGOV/po/nl-local.po
Updated Dutch translation for addon GetGOV.
=> [GetGOV] Dutch translation

HeadlineNewsGramplet/po/nl-local.po
Updated Dutch translation for addon HeadlineNewsGramplet.
=> [HeadlineNewsGramplet] Updated translation

HouseTimelineGramplet/housetimeline.py, HouseTimelineGramplet/po/nl-local.po
Dutch translation for addon HouseTimelineGramplet and a fix for localisation.
Tested with one issue in Gramps 5.1.2 on Linux Mint 20: the addon expects that Windows font 'Courier' is loaded, but that is not the case in a Linux system and most likely not in a Macintosh. To get the addon working, the font must now be changed manually in the code. Anyway, this has nothing to do with the translation and can be solved by someone later.
=> [HouseTimelineGramplet] Localisation fix and Dutch translation

ListeEclair/po/nl-local.po
Dutch translation for addon ListeEclair (not an update as original was empty).
=> [ListeEclair] Dutch translation.

MediaBrowser/po/nl-local.po
Dutch translation for addon MediaBrowser.
=> [MediaBrowser] Dutch translation

MediaMerge/mediamerge.gpr.py, MediaMerge/mediamerge.py, MediaMerge/po/nl-local.po
Localisation fix and Dutch translation for addon MediaMerge.
Tested in Gramps 5.1.2 on Linux Mint 20, but it is unfortunate that the tool does not give the opportunity to check the found duplicate media or to reverse the changes.
=> [MediaMerge] Localisation fix and Dutch translation

MediaVerify/po/nl-local.po
Dutch translation for addon MediaVerify.
=> [MediaVerify] Dutch translation.

MongoDB/po/nl-local.po
Dutch translation for addon MongoDB.
Not tested as this addon has status 'unstable' and is not listed in Gramps.
=> [MongoDB] Dutch translation

NumberOfDescendantsQuickview/po/nl-local.po
Updated Dutch translation for addon NumberOfDescendantsQuickview.
However, some words are not translated in the 'Generation' column, which come from another source. And the code from that source, relationship.py, must be edited before it can be translated. I'll look at that later...
=> [NumberOfDescendantsQuickview] Updated Dutch translation

Participants/po/nl-local.po
Dutch translation for addon Participants.
=> [Participants] Dutch translation

libwebconnect/po/nl-local.po
Modified Dutch translation for addon libwebconnect
=> [libwebconnect] Modified Dutch translation.

lxml/po/nl-local.po
Dutch translation for addon lxml.
=> [lxml] Dutch translation.

QuiltView/QuiltView.py, QuiltView/po/nl-local.po
Dutch translation for addon QuiltView.
Had to move parenthesis to get sentence 'You have %(filter)d filtered people, %(count)d people shown on the tree and "
"%(total)d people in your database.' translated. This modification doesn't have impact on other translations or template.pot.
=> [QuiltView] Dutch translation

RelID/po/nl-local.po
Dutch translation for addon RelID.
=> [RelID] Dutch translation.

RestoreHist/po/nl-local.po
Dutch translation for addon RestoreHist.
=> [RestoreHist] Dutch translation.

SourceReferences/po/nl-local.po
Dutch translation for addon SourceReferences.
=> [SourceReferences] Dutch translation.

ThumbnailGenerator/po/nl-local.po
Dutch translation for addon ThumbnailGenerator.
=> [ThumbnailGenerator] Dutch translation.

TimelineQuickview/po/nl-local.po
Updated Dutch translation for addon TimelineQuickview.
=> [TimelineQuickview] Updated Dutch translation.

Topola/po/nl-local.po
Dutch translation for addon Topola.
=> [Topola] Dutch translation.

USWebConnectPack/po/nl-local.po
Updated Dutch translation for addon USWebConnectPack.
=> [USWebConnectPack] Updated Dutch translation.

RemoveTagTool/RemoveTagTool.py, RemoveTagTool/po/de-local.po, RemoveTagTool/po/hr-local.po, RemoveTagTool/po/nl-local.po, RemoveTagTool/po/pt_PT-local.po, RemoveTagTool/po/ru-local.po, RemoveTagTool/po/template.pot
Fixed internationalization of addon RemoveTagTool.
Updated translations and template.pot.
=> [RemoveTagTool] Fix internationalization; DE, HR, NL, PT, RU translations.

EventDescriptionEditor/EventDescriptionEditor.py, EventDescriptionEditor/po/nl-local.po
Dutch translation for addon EventDescriptionEditor.
A 'close parenthesis' was in the wrong place causing the translation to fail, fixed on line 92.
=> [EventDescriptionEditor] Dutch translation

SyncAssociations/po/nl-local.po, SyncAssociations/syncAssociations.py
Dutch translation for addon SyncAssociations.
Although this tool has no dialogue with the user (which is bad and sometimes harmful), I did fix the localization anyway.
Tested in Gramps 5.1.3 on Linux Mint 20.
=> [SyncAssociations] Localization fix and Dutch translation

RUWebConnectPack/po/nl-local.po
Dutch translation for addon RUWebConnectPack.
=> [RUWebConnectPack] Dutch translation.

FilterRules/degreesofseparation.gpr.py, FilterRules/degreesofseparation.py
Rewrite to make it more intuitive as requested in:
https://gramps.discourse.group/t/degrees-of-separation-filter/148/17
The rule now searches recursivly for the parents, siblings, children and partners of a person, instead of using the rules "ancestors  less then N generations" and "descendants less than N generations".
=> Update filter rule "degrees of seperation"

DoubleCousins/double_cousins.gpr.py, DoubleCousins/double_cousins.py
New text report which lists double first cousins of the database. Double first cousins occur when two siblings of family A marry two siblings of family B.  Their children are double cousins to each other and share the same four grandparents.
The code checks for persons with known parents and grandparents, then checks for each combination if the two people have different parents but the same four grandparents.
[More discussion](https://gramps.discourse.group/t/searching-for-double-cousins/752) about finding double cousins in a Gramps database.
=> New text report [DoubleCousins]

SetPrivacyTool/SetPrivacyTool.py
Hi,
@Mattkmmr's set privacy tool is great, however I was missing one feature and noticed one problem. This PR fixes both:
1. It implements optionally applying custom filters to people, events, and handles. These filters are applied on top of the already existing options. Thanks to the very flexible filter system, they allow for very complex patterns.
2. I noticed the tool commits all objects it iterates over, even if it doesn't change them. This is bad (IMO) since it changes the last changed timestamp. In an extreme case, if it iterates over the entire DB and doesn't change any of the objects (e.g. because it wants to set them all public but they are already public), it still resets all the timestamps, so one looses all the information when an object was last modified.
=> SetPrivacyTool: add filters, don't touch if unchanged

FilterRules/activepersonrule.gpr.py, FilterRules/activepersonrule.py
This rule allows the user to create reports with a filter that includes the active person.  The filter will generate a warning (when run with no active person or from CLI).
=> New ActivePersonRule

EventDescriptionEditor/po/nl-local.po, FamilyRelationshipTool/po/nl-local.po
Updated Dutch translation for addon FamilyRelationshipTool.
=> FamilyRelationshipTool: update Dutch translation

EventDescriptionEditor/po/nl-local.po, FixCoords/po/nl-local.po
New Dutch translation for addon FixCoords.
NB. While this addon seems to work well, it could provide some more explanatory text.
For instance:
- the number of changed lines (even if nothing has been changed).
- what the tool is looking for exactly (I don't see any text during execution).
- what exactly the tool changed (it looks like it changes periods to commas).
Moreover, it seems to me that there should be a choice as to whether proposed changes are actually changed.
=> FixCoords: new Dutch translation

EventDescriptionEditor/po/nl-local.po, PhotoTaggingGramplet/po/nl-local.po
Updated Dutch translation for addon PhotoTaggingGramplet.
=> PhotoTaggingGramplet: update Dutch translation

EventDescriptionEditor/po/nl-local.po, PlaceCoordinateGramplet/po/nl-local.po
Updated Dutch translation for addon PlaceCoordinateGramplet.
=> PlaceCoordinateGramplet: update Dutch translation

EventDescriptionEditor/po/nl-local.po, TimePedigreeHTML/TimePedigreeHtml.gpr.py, TimePedigreeHTML/po/nl-local.po
Updated Dutch translation for addon TimePedigreeHtml.
Tested without issues in Gramps 5.1.3 on Linux Mint 20.1 after fixing TimePedigreeHtml.gpr.py, as the addon name in Gramps was not translated.
=> TimePedigreeHtml: new Dutch translation

PostgreSQL/postgresql.gpr.py, PostgreSQL/postgresql.py
Currently, the PostgreSQL plugin drops the existing collation and creates it again on each database connection. That shouldn't be necessary and creates [issues with Web API](https://github.com/gramps-project/gramps-webapi/issues/262). So this PR changes the behaviour to only create the collation for a given locale if it doesn't exist yet.
=> PostgreSQL: don't re-create collation if it already exists

FamilyTree/FamilyTree.py
If either mother or father person handles could not be obtained, don't try to get details about the person because it raises an exception and leads to the crashes described in the bug report.
Fixes [#12103](https://gramps-project.org/bugs/view.php?id=12103)
=> [FamilyTree]: Fixes #0012103 Validate person handle before using.

S3MediaUploader/S3MediaUploader.gpr.py, S3MediaUploader/S3MediaUploader.py
This add-on provides a command-line tool to upload media files to Amazon S3 or compatible object storage. It uses the file MD5 checksum as object key, avoiding storing duplicated files twice and ensuring files are always up to date.
The motivation for this add-on is a [planned feature for Gramps Web (API)](https://github.com/gramps-project/gramps-webapi/issues/237) to store media files on S3.
The easiest way to test this add-on (on Linux) is using a local S3-like server as provided by [S3 Ninja](https://s3ninja.net/):
```
docker run -p 9444:9000 scireum/s3-ninja:latest
```
Now open `http://localhost:9444/ui`, copy the access key and secret key and store them in environment variables
```
export AWS_ACCESS_KEY_ID=<your access key>
export AWS_SECRET_ACCESS_KEY=<your secret key>
```
You will …
=> Add S3 media uploader addon

SharedPostgreSQL/po/de-local.po, SharedPostgreSQL/po/hr-local.po, SharedPostgreSQL/po/nl-local.po, SharedPostgreSQL/po/pt_PT-local.po, SharedPostgreSQL/po/ru-local.po, SharedPostgreSQL/po/template.pot, SharedPostgreSQL/shareddbapi.py, SharedPostgreSQL/sharedpostgresql.gpr.py, SharedPostgreSQL/sharedpostgresql.py
This database add-on is a variation of the existing PostgreSQL add-on which allows to store an arbitrary number of family trees, rather than just a single one, in a Postgres database.
The original PostgreSQL add-on works as follows: it assumes the existince of a database with the name being the name of the family tree in Gramps. It then creates the database tables exactly like in the SQLite core module.
The new shared PostgreSQL add-on works on a single database (assumed to be named `gramps` by default). It has the same database tables as the original one, but adds a new column `treeid` to all tables and a new table `trees` with two columns: `treeid` and `uuid`. When a new family tree of type `sharedpostgresql` is created in Gramps, it generates a random UUIDv4, stores it in …
=> Add SharedPostgreSQL add-on

LifeLineChartView/lifelinechartview.gpr.py
switch to version 1.7.7 of life_line_chart module to fix python 10 compatibility
=> LifeLineChartView: update version to fix python 10 compatibility

CombinedView/basepage.py
If father handle can not be obtained, don't try to get details about the father because it raises an exception and leads to the crash described in the bug report.
Fixes [#11814](https://gramps-project.org/bugs/view.php?id=11814)
=> [CombinedView] Fixes #0011814 Validate father handle before using.

RepositoriesReport/RepositoriesReportAlt.py
In the source reference handles, we may have Tags
and perhaps other things.
Fixes #012764
=> Report "Repositories Report Options" crashes

PrerequisitesCheckerGramplet/PrerequisitesCheckerGramplet.gpr.py, PrerequisitesCheckerGramplet/PrerequisitesCheckerGramplet.py, PrerequisitesCheckerGramplet/README.md
1 -  New version imported from Bug report 012769
The text reformatting includes:
swapping in leading spaces & bullets for asterisks.
italicizing descriptive text
composing backup text and correcting menu labels
making the Required-Recommended-optional section labels more consistent in tense
Updated Help URLs
Changed & tested the Help URLs to the new standard "Addon:" prefix and added a
"in document" scrolling target. (Including the help_url in this repository's Gramps
Plugin's Registration file.)
2 -  PrerequisitesChecker gramplet: Gexiv2 and ICU
Detection of these libraries does not work or partially.
3 - If the Prerequisites Checker Gramplet is active when Gramps start, the Gramplet runs the report 3 times
Fixes #012767, #012769, #012770
=> New version of PrerequisiteCheckerGramplet and some troubleshooting.

Form/form_gb.xml
Add additional columns present on English death certificates from the 1970s and early 1980s
=> Add additional fields to UKDeath form definition

SharedPostgreSQL/shareddbapi.py, SharedPostgreSQL/sharedpostgresql.gpr.py
Dear maintainers,
I found this bug that breaks Gramps Web instances using the shared PostgreSQL addon. I would appreciate if you could merge this as soon as possible. Thanks a lot!
=> Fix missing space leading to syntax error

Form/form_gb.xml
(1) Mainly adding entries for 1921 England and Wales census forms. I tried to keep the headings as similar to 1911 as possible. A sample form (for England) [can be found here](https://webarchive.nationalarchives.gov.uk/ukgwa/20160105160709/http://www.ons.gov.uk/ons/guide-method/census/2011/how-our-census-works/about-censuses/census-history/200-years-of-the-census/census-1911-2001/1921-census-form.pdf).
Also: 
(2) Minor changes to 1911 England census form (spelling / consistency with headings on the documents)
(3) Copying changes previously made to 1891–1911 England census forms to the Wales census forms (these should be identical to the England entries save for the Language field)
(4) Minor changes to the Wales column widths for consistency with the England censuses
=> 1921 England & Wales census forms, plus minor changes

DNA/dnasegmentmap.py
Allow Association Note to use either ',' or '.' as thousands separator. Needed for German GEDmatch cut-paste.
=> Fix 0013012 - DNA Segment Map with TSV thousands separator

GetGOV/getgov.py
Address python warning:
plugins/GetGOV/getgov.py:352: SyntaxWarning: "is not" with a literal. Did you mean "!="?
if place.get_name().get_value is not '':
=> Update getgov.py for python change

MediaVerify/MediaVerify.py
[Environment variables in mediapath](https://github.com/gramps-project/gramps/pull/56) enabled support for the 'Base path for relative media paths:' to include relative paths (e.g. '../../../Media') or environment variables (e.g. '{GRAMPSHOME}/Media'). The current version of the 'Media Verify' add-on does not include this ability--this PR adds this support.
=> MediaVerify: add support for env variables in mediapath

DNAMatches/dnamatches.gpr.py, DNAMatches/dnamatches.py, DNAMatches/po/sk-local.po, DNAMatches/po/template.pot
Hey, I made this Gramplet for personal use but thought others may find it useful as well, so here it is. 
DNA Matches will list the active person's DNA matches including information about their relationship, cMs, number of segments, largest segment and sources. It is designed to complement the [DNA Segment Map](https://gramps-project.org/wiki/index.php/Addon:DNASegmentMapGramplet) and also works with the [Sync Associations](https://gramps-project.org/wiki/index.php/Addon:SyncAssociation) gramplet, but can be used without them. 
Information is gathered from Notes in Associations of type "DNA" between persons, same as with the DNA Segment Map (exact same format). However, there is also an alternative format for websites that don't have chromosome browsers such as Ancestry. This takes the …
=> New Gramplet: DNA matches (Gramps 5.1)

Form/form_gb.xml
The UK 1921 census form has separate columns for a persons age in  years and months.
Store these are separate columns in the gramps form definition.
The existing gramps UK1921 form Age column name has not been renamed to maintain backwards compatibility.
We have no way to know how someone may have encoded the years and months columns from the printed form into the single column in the gramps form. This makes it challenging to migrate existing data to the new structure.
=> Update 1921 England Census form: Separate age years and age months

Form/editform.py
Currently the date of the event object created by the form is set based on the form.
The date of the citation object is sometimes set.
This PR aligns the behaviour so that the citation date is always set
Currently there are two different behaviours:
1. if the form definition defined the date
the event and citation objects had the same date as the user is not able to edit the date in the form
therefore, they were always synced
2. if the form definition did not define a date
the event date was set based on the form dialog. 
the citation date was never set.
With this change, the citation date is aligned to the event date when saving the form
=> Form: Sync Event and Citation dates on save

Form/editform.py, Form/form.py, Form/form_gb.xml
Teach the Form gramplet about form specific default references. The anticipated use is for a form to optionally provide template text in the reference attribute. This text is then shown in the form GUI Reference field for the user to complete to create a fully formed reference.
The PR is broken into 3 commits:
1. read the new 'reference' attribute from the form XML file and store in the Form class
2. display a forms reference in the GUI, but only for new forms
3. add template references to a selection of forms defined in form_gb.xml
Fully backwards compatible with existing form definitions. If the reference attribute is missing from the form XML, existing behaviour is maintained.
=> Form references[v52]

GedcomExtensions/GedcomExtensions.py, GedcomExtensions/po/da-local.po, GedcomExtensions/po/de-local.po, GedcomExtensions/po/fi-local.po, GedcomExtensions/po/fr-local.po, GedcomExtensions/po/hr-local.po, GedcomExtensions/po/nl-local.po, GedcomExtensions/po/pt_PT-local.po, GedcomExtensions/po/ru-local.po, GedcomExtensions/po/sv-local.po, GedcomExtensions/po/template.pot
Fix for "0013546: Gramps produces unusable GEDCOM when patronymic names are used"
https://gramps-project.org/bugs/view.php?id=13546
This adds options
1. Don't change Gramps export
2. Export Patronymic after given name, instead of adding it to the list of surnames
3. Ignore Patronymic names on export
Sample person
1. Don't change Gramps export
```
0 HEAD
1 SOUR Gramps
2 VERS AIO64-5.2.3-r1-aa03f5a
2 NAME Gramps
1 DATE 2 JAN 2025
2 TIME 22:00:48
1 SUBM @SUBM@
1 FILE C:\Users\x\Downloads\test_noop.ged2
1 COPR Copyright (c) 2025 .
1 GEDC
2 VERS 5.5.1
2 FORM LINEAGE-LINKED
1 CHAR UTF-8
1 LANG English
0 @SUBM@ SUBM
1 NAME
0 @I0000@ INDI
1 NAME Fyodor /Dostoevsky Mikhailovich/
2 TYPE birth
2 GIVN Fyodor
2 SURN Dostoevsky, Mikhailovich
1 SEX M
1 CHAN
2 DATE 2 JAN 2025
3 TIME 21:57:36
0 TRLR
``` …
=> Update GedcomExtensions plugin to unblock GEDCOM exports with patronymic names

Form/editform.py
Gramps 5.2, introduced a regression when closing the EditForm dialog, if an image from the gallery had been selected.
This is logged in [mantis](https://gramps-project.org/bugs/view.php?id=13326) and discussed in the forum [here](https://gramps.discourse.group/t/repeatable-unexpected-error-gallery-in-forms/6436/8) and [here](https://gramps.discourse.group/t/error-gallerytab-object-has-no-attribute-iconlist/6675/7).
**Minimal steps to reproduce**
1. install the Forms addon
2. configure at least one Source to be a form
3. create a new form
4. in the form dialog, switch to the gallery tab
5. add an image
6. select the image you just added
7. click Cancel on the Form dialog
It can also be reproduced by opening an existing form with an image and following steps 4, 6 and 7
**Investigation**
I …
=> Tentative fix for crash in Form editor

DateCalculator/DateCalculator.py
Pressing the enter or keypad-enter keys in either of the two entry widgets now acts the same as clicking the Calculate button.
Typically your hand will be on the keyboard to enter the second date value. Pressing enter can be a quicker and more convenient way to trigger calculation than existing methods:
1. moving your hand back to the mouse, moving the mouse over the Calculate button and clicking it. 
2. pressing tab twice to move the input focus to the Calculate button and press enter
Both these methods continue to work
=> DateCalculator: Make the enter key trigger calculation

GedcomExtensions/GedcomExtensions.py
Bug (tweak): https://gramps-project.org/bugs/view.php?id=13574
[GedcomExtensions](https://github.com/bryndin/addons-source/tree/maintenance/gramps52/GedcomExtensions) provides tools to enhance the default GEDCOM export. Users decide what tools they need. By default, GedcomExtensions must behave exactly like the vanilla exporter, and users can enable what they need. Thus, I'm changing the defaults for some features from ON to OFF.
**Change: "Include witnesses" and "Include media" checkboxes are disabled upon start**
Behavior before the change:
After the change:
=> GedcomExt: Change defaults from extra options from ON to OFF

GedcomExtensions/GedcomExtensions.py, GedcomExtensions/po/da-local.po, GedcomExtensions/po/de-local.po, GedcomExtensions/po/fi-local.po, GedcomExtensions/po/fr-local.po, GedcomExtensions/po/hr-local.po, GedcomExtensions/po/nl-local.po, GedcomExtensions/po/pt_PT-local.po, GedcomExtensions/po/ru-local.po, GedcomExtensions/po/sv-local.po, GedcomExtensions/po/template.pot
Bug: https://gramps-project.org/bugs/view.php?id=13575
In Gramps surnames can be tagged with "inherited", "taken", "patronymic" etc. That tagging is not supported by GEDCOM and is lost during the export. The surnames end up space separated and create confusion when imported to other services (e.g. Geni, FamilySearch, etc.)
Example:
Maria (given) Skłodowska (inherited surname) Curie (taken surname)
```
0 @I0003@ INDI
1 NAME Maria /Skłodowska Curie/
2 TYPE birth
2 GIVN Maria
2 SURN Skłodowska, Curie
```
Fyodor (given), Dostoevsky(inherited surname) Mikhailovich (patronymic surname)
```
0 @I0004@ INDI
1 NAME Fyodor /Dostoevsky Mikhailovich/
2 TYPE birth
2 GIVN Fyodor
2 SURN Dostoevsky, Mikhailovich
```
It's customary in gene research to only use "maiden" names and many services expect that. …
=> [GedcomExtensions] Allow exporting only one type of surnames

SearchGramplet/SearchGramplet.gpr.py, SearchGramplet/SearchGramplet.py
SearchGramplet based on GraphView search widget.
Road map:
=> Add SearchGramplet

DescendantBooks/DescendantBookReport.py, DescendantBooks/DetailedDescendantBookReport.py, DescendantBooks/po/template.pot
Fixes [#13663](https://gramps-project.org/bugs/view.php?id=13663).
=> Fix format string with unnamed arguments warnings

lxml/lxmlGramplet.py
same as #685 but for gramps60
self.text will be a list after the first run (list of media object references). So, we are no more able to run a second pass after the first one. It does not make sense to re-run the gramplet, but this PR should fix this issue.
=> Fix second run (gramps60)

lxml/lxmlGramplet.py
self.text will be a list after the first run (list of media object references). So, we are no more able to run a second pass after the first one. It does not make sense to re-run the gramplet, but this PR should fix this issue.
=> Fix second run

HouseTimelineGramplet/housetimeline.gpr.py, HouseTimelineGramplet/housetimeline.py
Add "Emoji" house option and make default
Improve divider from "equals" symbol to horizontal bar
Increase Courier font from 9pt to 12pt
=> emoji default for House Timeline Gramplet

DetDescendantReport-images/detdescendantreporti.py
Added _format_source_text and _format_ref_text since calling protected procedure is not part of public API
=> Fix reference to _format_source_text in DetailedDescendantReport with Images

make.py
Been looking at the translation automation in make.
Big one, it looks like the extracted po files don't contain .pot msgid strings that should be satisfied from the Gramps main translations.  You stripped those out of the overall pot, to reduce translation work, good.
But when you did the extraction of main po files to individual addons, the Gramps strings were not included.
A smaller issue, Windows system (mine at least) doesn't include a "touch" command.
Also on Windows, you have to specify utf8 when opening a file or you get errors due to default code page.
I also added the ability to do a single file "as-needed", but may still want to enhance further with updated po etc. when the Weblate changes settle down.
I suspect that some of the other commands will fail for the 'all' when they …
=> Some fixes and enhancements for the make file

DescendantsLines/DescendantsLines.py
This adds the option to resize the text and change the font of the DescendantsLines report. The default text size is so small, that after printing the report on a bigger scale the text is very blurry
The font name in windows is the name of the `.ttf` file at `\Windows\Fonts\..`, in Linux you can check `fontconfig`.
=> added font name & size settings to DescendantsLines report

lxml/etreeGramplet.py, lxml/lxmlGramplet.py
* Provide support for options on `lxml gramplet` (String and Boolean). Most are related to xmllint options (arguments/flags). So command line could be more flexible. Also, set '--nonet' as default option. This should limit ping via the web for looking at dtd file. Two options are related to debug, either on place name or more global on xml or use of 3rd party lib (xmltodict).
* Fix a remaining issue on the word 'Edition', which is not correct in English. I missed one translation string on the label for options on `etree gramplet`
=> Options support for lxml gramplet and fix wording on etree gramplet

TimePedigreeHTML/TimePedigreeHtml.gpr.py, TimePedigreeHTML/TimePedigreeHtml.py
This pull request for "Timeline Pedigree Report" addon: 
* make the addon compatible with both 5.2 and 6.0 gramps's releases.
* correct a little bug : file bg.jpg was not copied to target destination.
=> "Timeline Pedigree Report" : changes for gramps 6.0, and bug correction for background

DescendantBooks/DetailedDescendantBookReport.py
Fixes [#13705](https://gramps-project.org/bugs/view.php?id=13705)
This change resolves syntax errors introduced by a prior submission which prevented the book report from loading.
=> Fix error that prevented loading Descendant Book Report

Form/form_us.xml
This PR replaces [542](https://github.com/gramps-project/addons-source/pull/542) with similar changes to the US WWII Draft Registration Form for the gramps60 branch. It rebases the changes (fixing some previous typos). It is backward compatible and does not break current usage.
The intention is to CLOSE [312](https://github.com/gramps-project/addons-source/pull/312), [542](https://github.com/gramps-project/addons-source/pull/542), and [546](https://github.com/gramps-project/addons-source/pull/546). This PR covers the Draft changes. The 1950 US Census changes will be discarded as they break current users.
=> Update WWII Draft Reg form based on PR 542

Form/form.py, Form/form_us.xml
A closing `</form>` tag is missing from the file. This causes the Form gramplet to fail to load.
Fixes bug [13820](https://gramps-project.org/bugs/view.php?id=13820)
=> Form gramplet: Fix malformed form_us.xml file

GrampsWebSync/webapihandler.py
In some cases, file uploads may fail due to temporary network issues or a restart of one of the pods running Gramps Web. When this happens, the entire sync process fails, requiring a full restart. This involves refetching remote data, comparing changes, and attempting to re-upload missing files — a time-consuming process, especially with large trees (as in my case).
This PR adds a one-time retry on network-related exceptions during file upload to mitigate such temporary issues and improve reliability.
=> Add one time retry on exception when file upload

PostgreSQL/postgresql.py
A Gramps Web user noticed that the PostgreSQL addon has not been adapted for Gramps 6.0 yet. (https://github.com/gramps-project/gramps-web-api/issues/637)
Note: this is not the SharedPostgreSQL addon that has been specifically develeoped for Gramps Web, but the old single-tree PostgreSQL addon.
Related discussion: https://github.com/gramps-project/gramps-web-api/issues/596#issuecomment-2623802281
Note that **I have not tested this change myself**.
The `drop_column` function is simple enough; the `column_exists` function has been copied over (and is identical to) the SharedPostgreSQL addon (which I have tested).
@dnightbane would you be able to test this?
CC @dsblank, @Nick-Hall
=> Adapt PostgreSQL addon for Gramps 6.0

SharedPostgreSQL/shareddbapi.py
I noticed that the `use_json` function errors out if the `metadata` column does not contain the `json_data` column yet. This fixes it.
=> Small fix to SharedPostgreSQL

SharedPostgreSQL/shareddbapi.py
Another small fix needed to make SharedPostgreSQL work fully with Gramps 6.0.
The issue here was that, if the tree has not been populated yet, `_schema_version_exists` would fail with an error.
@GaryGriffin it would be great if you could merge the fix swiftly, as usual :pray: Thanks!
=> Fix use_json_data in SharedPostgreSQL

CONTRIBUTING.md, MAINTAINERS.md
Add a CONTRIBUTING.md and MAINTAINERS.md file that describe the process for contributing an addon to addons-source, and maintaining the addons repo containing the packaged form of addons.
The content is also found on wiki pages (yet to be published) and has been reviewed by some of the current maintainers of these repositories.  I am offering these up as a DRAFT for further discussion and/or clarification.
=> Add contributor and maintainer documentation
